// Code generated by ent, DO NOT EDIT.

package checkpoint

import (
	"time"

	"beavermoney.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldID, id))
}

// HouseholdID applies equality check predicate on the "household_id" field. It's identical to HouseholdIDEQ.
func HouseholdID(v int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldHouseholdID, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldUpdateTime, v))
}

// NetWorth applies equality check predicate on the "net_worth" field. It's identical to NetWorthEQ.
func NetWorth(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldNetWorth, v))
}

// Liquidity applies equality check predicate on the "liquidity" field. It's identical to LiquidityEQ.
func Liquidity(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldLiquidity, v))
}

// Investment applies equality check predicate on the "investment" field. It's identical to InvestmentEQ.
func Investment(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldInvestment, v))
}

// Property applies equality check predicate on the "property" field. It's identical to PropertyEQ.
func Property(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldProperty, v))
}

// Receivable applies equality check predicate on the "receivable" field. It's identical to ReceivableEQ.
func Receivable(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldReceivable, v))
}

// Liability applies equality check predicate on the "liability" field. It's identical to LiabilityEQ.
func Liability(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldLiability, v))
}

// CurrencyID applies equality check predicate on the "currency_id" field. It's identical to CurrencyIDEQ.
func CurrencyID(v int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldCurrencyID, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldNote, v))
}

// HouseholdIDEQ applies the EQ predicate on the "household_id" field.
func HouseholdIDEQ(v int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldHouseholdID, v))
}

// HouseholdIDNEQ applies the NEQ predicate on the "household_id" field.
func HouseholdIDNEQ(v int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldHouseholdID, v))
}

// HouseholdIDIn applies the In predicate on the "household_id" field.
func HouseholdIDIn(vs ...int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldHouseholdID, vs...))
}

// HouseholdIDNotIn applies the NotIn predicate on the "household_id" field.
func HouseholdIDNotIn(vs ...int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldHouseholdID, vs...))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldUpdateTime, v))
}

// NetWorthEQ applies the EQ predicate on the "net_worth" field.
func NetWorthEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldNetWorth, v))
}

// NetWorthNEQ applies the NEQ predicate on the "net_worth" field.
func NetWorthNEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldNetWorth, v))
}

// NetWorthIn applies the In predicate on the "net_worth" field.
func NetWorthIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldNetWorth, vs...))
}

// NetWorthNotIn applies the NotIn predicate on the "net_worth" field.
func NetWorthNotIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldNetWorth, vs...))
}

// NetWorthGT applies the GT predicate on the "net_worth" field.
func NetWorthGT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldNetWorth, v))
}

// NetWorthGTE applies the GTE predicate on the "net_worth" field.
func NetWorthGTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldNetWorth, v))
}

// NetWorthLT applies the LT predicate on the "net_worth" field.
func NetWorthLT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldNetWorth, v))
}

// NetWorthLTE applies the LTE predicate on the "net_worth" field.
func NetWorthLTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldNetWorth, v))
}

// LiquidityEQ applies the EQ predicate on the "liquidity" field.
func LiquidityEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldLiquidity, v))
}

// LiquidityNEQ applies the NEQ predicate on the "liquidity" field.
func LiquidityNEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldLiquidity, v))
}

// LiquidityIn applies the In predicate on the "liquidity" field.
func LiquidityIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldLiquidity, vs...))
}

// LiquidityNotIn applies the NotIn predicate on the "liquidity" field.
func LiquidityNotIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldLiquidity, vs...))
}

// LiquidityGT applies the GT predicate on the "liquidity" field.
func LiquidityGT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldLiquidity, v))
}

// LiquidityGTE applies the GTE predicate on the "liquidity" field.
func LiquidityGTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldLiquidity, v))
}

// LiquidityLT applies the LT predicate on the "liquidity" field.
func LiquidityLT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldLiquidity, v))
}

// LiquidityLTE applies the LTE predicate on the "liquidity" field.
func LiquidityLTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldLiquidity, v))
}

// InvestmentEQ applies the EQ predicate on the "investment" field.
func InvestmentEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldInvestment, v))
}

// InvestmentNEQ applies the NEQ predicate on the "investment" field.
func InvestmentNEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldInvestment, v))
}

// InvestmentIn applies the In predicate on the "investment" field.
func InvestmentIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldInvestment, vs...))
}

// InvestmentNotIn applies the NotIn predicate on the "investment" field.
func InvestmentNotIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldInvestment, vs...))
}

// InvestmentGT applies the GT predicate on the "investment" field.
func InvestmentGT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldInvestment, v))
}

// InvestmentGTE applies the GTE predicate on the "investment" field.
func InvestmentGTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldInvestment, v))
}

// InvestmentLT applies the LT predicate on the "investment" field.
func InvestmentLT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldInvestment, v))
}

// InvestmentLTE applies the LTE predicate on the "investment" field.
func InvestmentLTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldInvestment, v))
}

// PropertyEQ applies the EQ predicate on the "property" field.
func PropertyEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldProperty, v))
}

// PropertyNEQ applies the NEQ predicate on the "property" field.
func PropertyNEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldProperty, v))
}

// PropertyIn applies the In predicate on the "property" field.
func PropertyIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldProperty, vs...))
}

// PropertyNotIn applies the NotIn predicate on the "property" field.
func PropertyNotIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldProperty, vs...))
}

// PropertyGT applies the GT predicate on the "property" field.
func PropertyGT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldProperty, v))
}

// PropertyGTE applies the GTE predicate on the "property" field.
func PropertyGTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldProperty, v))
}

// PropertyLT applies the LT predicate on the "property" field.
func PropertyLT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldProperty, v))
}

// PropertyLTE applies the LTE predicate on the "property" field.
func PropertyLTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldProperty, v))
}

// ReceivableEQ applies the EQ predicate on the "receivable" field.
func ReceivableEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldReceivable, v))
}

// ReceivableNEQ applies the NEQ predicate on the "receivable" field.
func ReceivableNEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldReceivable, v))
}

// ReceivableIn applies the In predicate on the "receivable" field.
func ReceivableIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldReceivable, vs...))
}

// ReceivableNotIn applies the NotIn predicate on the "receivable" field.
func ReceivableNotIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldReceivable, vs...))
}

// ReceivableGT applies the GT predicate on the "receivable" field.
func ReceivableGT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldReceivable, v))
}

// ReceivableGTE applies the GTE predicate on the "receivable" field.
func ReceivableGTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldReceivable, v))
}

// ReceivableLT applies the LT predicate on the "receivable" field.
func ReceivableLT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldReceivable, v))
}

// ReceivableLTE applies the LTE predicate on the "receivable" field.
func ReceivableLTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldReceivable, v))
}

// LiabilityEQ applies the EQ predicate on the "liability" field.
func LiabilityEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldLiability, v))
}

// LiabilityNEQ applies the NEQ predicate on the "liability" field.
func LiabilityNEQ(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldLiability, v))
}

// LiabilityIn applies the In predicate on the "liability" field.
func LiabilityIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldLiability, vs...))
}

// LiabilityNotIn applies the NotIn predicate on the "liability" field.
func LiabilityNotIn(vs ...decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldLiability, vs...))
}

// LiabilityGT applies the GT predicate on the "liability" field.
func LiabilityGT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldLiability, v))
}

// LiabilityGTE applies the GTE predicate on the "liability" field.
func LiabilityGTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldLiability, v))
}

// LiabilityLT applies the LT predicate on the "liability" field.
func LiabilityLT(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldLiability, v))
}

// LiabilityLTE applies the LTE predicate on the "liability" field.
func LiabilityLTE(v decimal.Decimal) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldLiability, v))
}

// CurrencyIDEQ applies the EQ predicate on the "currency_id" field.
func CurrencyIDEQ(v int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldCurrencyID, v))
}

// CurrencyIDNEQ applies the NEQ predicate on the "currency_id" field.
func CurrencyIDNEQ(v int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldCurrencyID, v))
}

// CurrencyIDIn applies the In predicate on the "currency_id" field.
func CurrencyIDIn(vs ...int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldCurrencyID, vs...))
}

// CurrencyIDNotIn applies the NotIn predicate on the "currency_id" field.
func CurrencyIDNotIn(vs ...int) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldCurrencyID, vs...))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Checkpoint {
	return predicate.Checkpoint(sql.FieldContainsFold(FieldNote, v))
}

// HasHousehold applies the HasEdge predicate on the "household" edge.
func HasHousehold() predicate.Checkpoint {
	return predicate.Checkpoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, HouseholdTable, HouseholdColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHouseholdWith applies the HasEdge predicate on the "household" edge with a given conditions (other predicates).
func HasHouseholdWith(preds ...predicate.Household) predicate.Checkpoint {
	return predicate.Checkpoint(func(s *sql.Selector) {
		step := newHouseholdStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCurrency applies the HasEdge predicate on the "currency" edge.
func HasCurrency() predicate.Checkpoint {
	return predicate.Checkpoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CurrencyTable, CurrencyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCurrencyWith applies the HasEdge predicate on the "currency" edge with a given conditions (other predicates).
func HasCurrencyWith(preds ...predicate.Currency) predicate.Checkpoint {
	return predicate.Checkpoint(func(s *sql.Selector) {
		step := newCurrencyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Checkpoint) predicate.Checkpoint {
	return predicate.Checkpoint(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Checkpoint) predicate.Checkpoint {
	return predicate.Checkpoint(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Checkpoint) predicate.Checkpoint {
	return predicate.Checkpoint(sql.NotPredicates(p))
}
