package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"beavermoney.app/ent"
	"entgo.io/contrib/entgql"
	"github.com/shopspring/decimal"
)

// Balance is the resolver for the balance field.
func (r *accountResolver) Balance(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.Balance.String(), nil
}

// Value is the resolver for the value field.
func (r *accountResolver) Value(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.Value.String(), nil
}

// FxRate is the resolver for the fxRate field.
func (r *accountResolver) FxRate(ctx context.Context, obj *ent.Account) (string, error) {
	return obj.FxRate.String(), nil
}

// NetWorth is the resolver for the netWorth field.
func (r *checkpointResolver) NetWorth(ctx context.Context, obj *ent.Checkpoint) (string, error) {
	return obj.NetWorth.String(), nil
}

// Liquidity is the resolver for the liquidity field.
func (r *checkpointResolver) Liquidity(ctx context.Context, obj *ent.Checkpoint) (string, error) {
	return obj.Liquidity.String(), nil
}

// Investment is the resolver for the investment field.
func (r *checkpointResolver) Investment(ctx context.Context, obj *ent.Checkpoint) (string, error) {
	return obj.Investment.String(), nil
}

// Property is the resolver for the property field.
func (r *checkpointResolver) Property(ctx context.Context, obj *ent.Checkpoint) (string, error) {
	return obj.Property.String(), nil
}

// Receivable is the resolver for the receivable field.
func (r *checkpointResolver) Receivable(ctx context.Context, obj *ent.Checkpoint) (string, error) {
	return obj.Receivable.String(), nil
}

// Liability is the resolver for the liability field.
func (r *checkpointResolver) Liability(ctx context.Context, obj *ent.Checkpoint) (string, error) {
	return obj.Liability.String(), nil
}

// Amount is the resolver for the amount field.
func (r *investmentResolver) Amount(ctx context.Context, obj *ent.Investment) (string, error) {
	return obj.Amount.String(), nil
}

// Quote is the resolver for the quote field.
func (r *investmentResolver) Quote(ctx context.Context, obj *ent.Investment) (string, error) {
	return obj.Quote.String(), nil
}

// Value is the resolver for the value field.
func (r *investmentResolver) Value(ctx context.Context, obj *ent.Investment) (string, error) {
	return obj.Value.String(), nil
}

// Amount is the resolver for the amount field.
func (r *investmentLotResolver) Amount(ctx context.Context, obj *ent.InvestmentLot) (string, error) {
	return obj.Amount.String(), nil
}

// Price is the resolver for the price field.
func (r *investmentLotResolver) Price(ctx context.Context, obj *ent.InvestmentLot) (string, error) {
	return obj.Price.String(), nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	return r.entClient.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	return r.entClient.Noders(ctx, ids)
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.AccountWhereInput) (*ent.AccountConnection, error) {
	return r.entClient.Account.Query().Paginate(ctx, after, first, before, last, ent.WithAccountFilter(where.Filter))
}

// Checkpoints is the resolver for the checkpoints field.
func (r *queryResolver) Checkpoints(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.CheckpointWhereInput) (*ent.CheckpointConnection, error) {
	return r.entClient.Checkpoint.Query().Paginate(ctx, after, first, before, last, ent.WithCheckpointFilter(where.Filter))
}

// Currencies is the resolver for the currencies field.
func (r *queryResolver) Currencies(ctx context.Context) ([]*ent.Currency, error) {
	return r.entClient.Currency.Query().All(ctx)
}

// Households is the resolver for the households field.
func (r *queryResolver) Households(ctx context.Context) ([]*ent.Household, error) {
	return r.entClient.Household.Query().All(ctx)
}

// Investments is the resolver for the investments field.
func (r *queryResolver) Investments(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.InvestmentWhereInput) (*ent.InvestmentConnection, error) {
	return r.entClient.Investment.Query().Paginate(ctx, after, first, before, last, ent.WithInvestmentFilter(where.Filter))
}

// InvestmentLots is the resolver for the investmentLots field.
func (r *queryResolver) InvestmentLots(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.InvestmentLotWhereInput) (*ent.InvestmentLotConnection, error) {
	return r.entClient.InvestmentLot.Query().Paginate(ctx, after, first, before, last, ent.WithInvestmentLotFilter(where.Filter))
}

// RecurringSubscriptions is the resolver for the recurringSubscriptions field.
func (r *queryResolver) RecurringSubscriptions(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.RecurringSubscriptionWhereInput) (*ent.RecurringSubscriptionConnection, error) {
	return r.entClient.RecurringSubscription.Query().Paginate(ctx, after, first, before, last, ent.WithRecurringSubscriptionFilter(where.Filter))
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.TransactionOrder, where *ent.TransactionWhereInput) (*ent.TransactionConnection, error) {
	return r.entClient.Transaction.Query().Paginate(ctx, after, first, before, last, ent.WithTransactionOrder(orderBy), ent.WithTransactionFilter(where.Filter))
}

// TransactionCategories is the resolver for the transactionCategories field.
func (r *queryResolver) TransactionCategories(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.TransactionCategoryWhereInput) (*ent.TransactionCategoryConnection, error) {
	return r.entClient.TransactionCategory.Query().Paginate(ctx, after, first, before, last, ent.WithTransactionCategoryFilter(where.Filter))
}

// TransactionEntries is the resolver for the transactionEntries field.
func (r *queryResolver) TransactionEntries(ctx context.Context) ([]*ent.TransactionEntry, error) {
	return r.entClient.TransactionEntry.Query().All(ctx)
}

// UserHouseholds is the resolver for the userHouseholds field.
func (r *queryResolver) UserHouseholds(ctx context.Context) ([]*ent.UserHousehold, error) {
	return r.entClient.UserHousehold.Query().All(ctx)
}

// Cost is the resolver for the cost field.
func (r *recurringSubscriptionResolver) Cost(ctx context.Context, obj *ent.RecurringSubscription) (string, error) {
	return obj.Cost.String(), nil
}

// FxRate is the resolver for the fxRate field.
func (r *recurringSubscriptionResolver) FxRate(ctx context.Context, obj *ent.RecurringSubscription) (string, error) {
	return obj.FxRate.String(), nil
}

// Amount is the resolver for the amount field.
func (r *transactionEntryResolver) Amount(ctx context.Context, obj *ent.TransactionEntry) (string, error) {
	return obj.Amount.String(), nil
}

// Balance is the resolver for the balance field.
func (r *accountWhereInputResolver) Balance(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	if data == nil || *data == "" {
		return nil
	}

	dec, err := decimal.NewFromString(*data)
	if err != nil {
		return fmt.Errorf("invalid decimal string for balance: %v", err)
	}

	obj.Balance = &dec
	return nil
}

// BalanceNeq is the resolver for the balanceNEQ field.
func (r *accountWhereInputResolver) BalanceNeq(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: BalanceNeq - balanceNEQ"))
}

// BalanceIn is the resolver for the balanceIn field.
func (r *accountWhereInputResolver) BalanceIn(ctx context.Context, obj *ent.AccountWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: BalanceIn - balanceIn"))
}

// BalanceNotIn is the resolver for the balanceNotIn field.
func (r *accountWhereInputResolver) BalanceNotIn(ctx context.Context, obj *ent.AccountWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: BalanceNotIn - balanceNotIn"))
}

// BalanceGt is the resolver for the balanceGT field.
func (r *accountWhereInputResolver) BalanceGt(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: BalanceGt - balanceGT"))
}

// BalanceGte is the resolver for the balanceGTE field.
func (r *accountWhereInputResolver) BalanceGte(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: BalanceGte - balanceGTE"))
}

// BalanceLt is the resolver for the balanceLT field.
func (r *accountWhereInputResolver) BalanceLt(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: BalanceLt - balanceLT"))
}

// BalanceLte is the resolver for the balanceLTE field.
func (r *accountWhereInputResolver) BalanceLte(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: BalanceLte - balanceLTE"))
}

// Value is the resolver for the value field.
func (r *accountWhereInputResolver) Value(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Value - value"))
}

// ValueNeq is the resolver for the valueNEQ field.
func (r *accountWhereInputResolver) ValueNeq(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueNeq - valueNEQ"))
}

// ValueIn is the resolver for the valueIn field.
func (r *accountWhereInputResolver) ValueIn(ctx context.Context, obj *ent.AccountWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: ValueIn - valueIn"))
}

// ValueNotIn is the resolver for the valueNotIn field.
func (r *accountWhereInputResolver) ValueNotIn(ctx context.Context, obj *ent.AccountWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: ValueNotIn - valueNotIn"))
}

// ValueGt is the resolver for the valueGT field.
func (r *accountWhereInputResolver) ValueGt(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueGt - valueGT"))
}

// ValueGte is the resolver for the valueGTE field.
func (r *accountWhereInputResolver) ValueGte(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueGte - valueGTE"))
}

// ValueLt is the resolver for the valueLT field.
func (r *accountWhereInputResolver) ValueLt(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueLt - valueLT"))
}

// ValueLte is the resolver for the valueLTE field.
func (r *accountWhereInputResolver) ValueLte(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueLte - valueLTE"))
}

// FxRate is the resolver for the fxRate field.
func (r *accountWhereInputResolver) FxRate(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRate - fxRate"))
}

// FxRateNeq is the resolver for the fxRateNEQ field.
func (r *accountWhereInputResolver) FxRateNeq(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateNeq - fxRateNEQ"))
}

// FxRateIn is the resolver for the fxRateIn field.
func (r *accountWhereInputResolver) FxRateIn(ctx context.Context, obj *ent.AccountWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: FxRateIn - fxRateIn"))
}

// FxRateNotIn is the resolver for the fxRateNotIn field.
func (r *accountWhereInputResolver) FxRateNotIn(ctx context.Context, obj *ent.AccountWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: FxRateNotIn - fxRateNotIn"))
}

// FxRateGt is the resolver for the fxRateGT field.
func (r *accountWhereInputResolver) FxRateGt(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateGt - fxRateGT"))
}

// FxRateGte is the resolver for the fxRateGTE field.
func (r *accountWhereInputResolver) FxRateGte(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateGte - fxRateGTE"))
}

// FxRateLt is the resolver for the fxRateLT field.
func (r *accountWhereInputResolver) FxRateLt(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateLt - fxRateLT"))
}

// FxRateLte is the resolver for the fxRateLTE field.
func (r *accountWhereInputResolver) FxRateLte(ctx context.Context, obj *ent.AccountWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateLte - fxRateLTE"))
}

// NetWorth is the resolver for the netWorth field.
func (r *checkpointWhereInputResolver) NetWorth(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: NetWorth - netWorth"))
}

// NetWorthNeq is the resolver for the netWorthNEQ field.
func (r *checkpointWhereInputResolver) NetWorthNeq(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: NetWorthNeq - netWorthNEQ"))
}

// NetWorthIn is the resolver for the netWorthIn field.
func (r *checkpointWhereInputResolver) NetWorthIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: NetWorthIn - netWorthIn"))
}

// NetWorthNotIn is the resolver for the netWorthNotIn field.
func (r *checkpointWhereInputResolver) NetWorthNotIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: NetWorthNotIn - netWorthNotIn"))
}

// NetWorthGt is the resolver for the netWorthGT field.
func (r *checkpointWhereInputResolver) NetWorthGt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: NetWorthGt - netWorthGT"))
}

// NetWorthGte is the resolver for the netWorthGTE field.
func (r *checkpointWhereInputResolver) NetWorthGte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: NetWorthGte - netWorthGTE"))
}

// NetWorthLt is the resolver for the netWorthLT field.
func (r *checkpointWhereInputResolver) NetWorthLt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: NetWorthLt - netWorthLT"))
}

// NetWorthLte is the resolver for the netWorthLTE field.
func (r *checkpointWhereInputResolver) NetWorthLte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: NetWorthLte - netWorthLTE"))
}

// Liquidity is the resolver for the liquidity field.
func (r *checkpointWhereInputResolver) Liquidity(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Liquidity - liquidity"))
}

// LiquidityNeq is the resolver for the liquidityNEQ field.
func (r *checkpointWhereInputResolver) LiquidityNeq(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiquidityNeq - liquidityNEQ"))
}

// LiquidityIn is the resolver for the liquidityIn field.
func (r *checkpointWhereInputResolver) LiquidityIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: LiquidityIn - liquidityIn"))
}

// LiquidityNotIn is the resolver for the liquidityNotIn field.
func (r *checkpointWhereInputResolver) LiquidityNotIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: LiquidityNotIn - liquidityNotIn"))
}

// LiquidityGt is the resolver for the liquidityGT field.
func (r *checkpointWhereInputResolver) LiquidityGt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiquidityGt - liquidityGT"))
}

// LiquidityGte is the resolver for the liquidityGTE field.
func (r *checkpointWhereInputResolver) LiquidityGte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiquidityGte - liquidityGTE"))
}

// LiquidityLt is the resolver for the liquidityLT field.
func (r *checkpointWhereInputResolver) LiquidityLt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiquidityLt - liquidityLT"))
}

// LiquidityLte is the resolver for the liquidityLTE field.
func (r *checkpointWhereInputResolver) LiquidityLte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiquidityLte - liquidityLTE"))
}

// Investment is the resolver for the investment field.
func (r *checkpointWhereInputResolver) Investment(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Investment - investment"))
}

// InvestmentNeq is the resolver for the investmentNEQ field.
func (r *checkpointWhereInputResolver) InvestmentNeq(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: InvestmentNeq - investmentNEQ"))
}

// InvestmentIn is the resolver for the investmentIn field.
func (r *checkpointWhereInputResolver) InvestmentIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: InvestmentIn - investmentIn"))
}

// InvestmentNotIn is the resolver for the investmentNotIn field.
func (r *checkpointWhereInputResolver) InvestmentNotIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: InvestmentNotIn - investmentNotIn"))
}

// InvestmentGt is the resolver for the investmentGT field.
func (r *checkpointWhereInputResolver) InvestmentGt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: InvestmentGt - investmentGT"))
}

// InvestmentGte is the resolver for the investmentGTE field.
func (r *checkpointWhereInputResolver) InvestmentGte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: InvestmentGte - investmentGTE"))
}

// InvestmentLt is the resolver for the investmentLT field.
func (r *checkpointWhereInputResolver) InvestmentLt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: InvestmentLt - investmentLT"))
}

// InvestmentLte is the resolver for the investmentLTE field.
func (r *checkpointWhereInputResolver) InvestmentLte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: InvestmentLte - investmentLTE"))
}

// Property is the resolver for the property field.
func (r *checkpointWhereInputResolver) Property(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Property - property"))
}

// PropertyNeq is the resolver for the propertyNEQ field.
func (r *checkpointWhereInputResolver) PropertyNeq(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PropertyNeq - propertyNEQ"))
}

// PropertyIn is the resolver for the propertyIn field.
func (r *checkpointWhereInputResolver) PropertyIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: PropertyIn - propertyIn"))
}

// PropertyNotIn is the resolver for the propertyNotIn field.
func (r *checkpointWhereInputResolver) PropertyNotIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: PropertyNotIn - propertyNotIn"))
}

// PropertyGt is the resolver for the propertyGT field.
func (r *checkpointWhereInputResolver) PropertyGt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PropertyGt - propertyGT"))
}

// PropertyGte is the resolver for the propertyGTE field.
func (r *checkpointWhereInputResolver) PropertyGte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PropertyGte - propertyGTE"))
}

// PropertyLt is the resolver for the propertyLT field.
func (r *checkpointWhereInputResolver) PropertyLt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PropertyLt - propertyLT"))
}

// PropertyLte is the resolver for the propertyLTE field.
func (r *checkpointWhereInputResolver) PropertyLte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PropertyLte - propertyLTE"))
}

// Receivable is the resolver for the receivable field.
func (r *checkpointWhereInputResolver) Receivable(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Receivable - receivable"))
}

// ReceivableNeq is the resolver for the receivableNEQ field.
func (r *checkpointWhereInputResolver) ReceivableNeq(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ReceivableNeq - receivableNEQ"))
}

// ReceivableIn is the resolver for the receivableIn field.
func (r *checkpointWhereInputResolver) ReceivableIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: ReceivableIn - receivableIn"))
}

// ReceivableNotIn is the resolver for the receivableNotIn field.
func (r *checkpointWhereInputResolver) ReceivableNotIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: ReceivableNotIn - receivableNotIn"))
}

// ReceivableGt is the resolver for the receivableGT field.
func (r *checkpointWhereInputResolver) ReceivableGt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ReceivableGt - receivableGT"))
}

// ReceivableGte is the resolver for the receivableGTE field.
func (r *checkpointWhereInputResolver) ReceivableGte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ReceivableGte - receivableGTE"))
}

// ReceivableLt is the resolver for the receivableLT field.
func (r *checkpointWhereInputResolver) ReceivableLt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ReceivableLt - receivableLT"))
}

// ReceivableLte is the resolver for the receivableLTE field.
func (r *checkpointWhereInputResolver) ReceivableLte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ReceivableLte - receivableLTE"))
}

// Liability is the resolver for the liability field.
func (r *checkpointWhereInputResolver) Liability(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Liability - liability"))
}

// LiabilityNeq is the resolver for the liabilityNEQ field.
func (r *checkpointWhereInputResolver) LiabilityNeq(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiabilityNeq - liabilityNEQ"))
}

// LiabilityIn is the resolver for the liabilityIn field.
func (r *checkpointWhereInputResolver) LiabilityIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: LiabilityIn - liabilityIn"))
}

// LiabilityNotIn is the resolver for the liabilityNotIn field.
func (r *checkpointWhereInputResolver) LiabilityNotIn(ctx context.Context, obj *ent.CheckpointWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: LiabilityNotIn - liabilityNotIn"))
}

// LiabilityGt is the resolver for the liabilityGT field.
func (r *checkpointWhereInputResolver) LiabilityGt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiabilityGt - liabilityGT"))
}

// LiabilityGte is the resolver for the liabilityGTE field.
func (r *checkpointWhereInputResolver) LiabilityGte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiabilityGte - liabilityGTE"))
}

// LiabilityLt is the resolver for the liabilityLT field.
func (r *checkpointWhereInputResolver) LiabilityLt(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiabilityLt - liabilityLT"))
}

// LiabilityLte is the resolver for the liabilityLTE field.
func (r *checkpointWhereInputResolver) LiabilityLte(ctx context.Context, obj *ent.CheckpointWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LiabilityLte - liabilityLTE"))
}

// Balance is the resolver for the balance field.
func (r *createAccountInputResolver) Balance(ctx context.Context, obj *ent.CreateAccountInput, data *string) error {
	if data == nil || *data == "" {
		return nil
	}

	dec, err := decimal.NewFromString(*data)
	if err != nil {
		return fmt.Errorf("invalid decimal string for balance: %v", err)
	}

	obj.Balance = &dec
	return nil
}

// Amount is the resolver for the amount field.
func (r *createInvestmentInputResolver) Amount(ctx context.Context, obj *ent.CreateInvestmentInput, data *string) error {
	if data == nil || *data == "" {
		return nil
	}

	dec, err := decimal.NewFromString(*data)
	if err != nil {
		return fmt.Errorf("invalid decimal string for amount: %v", err)
	}

	obj.Amount = &dec
	return nil
}

// Amount is the resolver for the amount field.
func (r *createInvestmentLotInputResolver) Amount(ctx context.Context, obj *ent.CreateInvestmentLotInput, data string) error {
	dec, err := decimal.NewFromString(data)
	if err != nil {
		return fmt.Errorf("invalid decimal string for amount: %v", err)
	}

	if dec.IsZero() {
		return fmt.Errorf("investment lot amount cannot be zero")
	}

	obj.Amount = dec
	return nil
}

// Price is the resolver for the price field.
func (r *createInvestmentLotInputResolver) Price(ctx context.Context, obj *ent.CreateInvestmentLotInput, data string) error {
	dec, err := decimal.NewFromString(data)
	if err != nil {
		return fmt.Errorf("invalid decimal string for price: %v", err)
	}

	obj.Price = dec
	return nil
}

// Cost is the resolver for the cost field.
func (r *createRecurringSubscriptionInputResolver) Cost(ctx context.Context, obj *ent.CreateRecurringSubscriptionInput, data *string) error {
	if data == nil || *data == "" {
		return nil
	}

	dec, err := decimal.NewFromString(*data)
	if err != nil {
		return fmt.Errorf("invalid decimal string for cost: %v", err)
	}

	obj.Cost = &dec
	return nil
}

// Amount is the resolver for the amount field.
func (r *createTransactionEntryInputResolver) Amount(ctx context.Context, obj *ent.CreateTransactionEntryInput, data string) error {
	dec, err := decimal.NewFromString(data)
	if err != nil {
		return fmt.Errorf("invalid decimal string for amount: %v", err)
	}

	if dec.IsZero() {
		return fmt.Errorf("transaction entry amount cannot be zero")
	}

	obj.Amount = dec
	return nil
}

// Amount is the resolver for the amount field.
func (r *investmentLotWhereInputResolver) Amount(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Amount - amount"))
}

// AmountNeq is the resolver for the amountNEQ field.
func (r *investmentLotWhereInputResolver) AmountNeq(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountNeq - amountNEQ"))
}

// AmountIn is the resolver for the amountIn field.
func (r *investmentLotWhereInputResolver) AmountIn(ctx context.Context, obj *ent.InvestmentLotWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: AmountIn - amountIn"))
}

// AmountNotIn is the resolver for the amountNotIn field.
func (r *investmentLotWhereInputResolver) AmountNotIn(ctx context.Context, obj *ent.InvestmentLotWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: AmountNotIn - amountNotIn"))
}

// AmountGt is the resolver for the amountGT field.
func (r *investmentLotWhereInputResolver) AmountGt(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountGt - amountGT"))
}

// AmountGte is the resolver for the amountGTE field.
func (r *investmentLotWhereInputResolver) AmountGte(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountGte - amountGTE"))
}

// AmountLt is the resolver for the amountLT field.
func (r *investmentLotWhereInputResolver) AmountLt(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountLt - amountLT"))
}

// AmountLte is the resolver for the amountLTE field.
func (r *investmentLotWhereInputResolver) AmountLte(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountLte - amountLTE"))
}

// Price is the resolver for the price field.
func (r *investmentLotWhereInputResolver) Price(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Price - price"))
}

// PriceNeq is the resolver for the priceNEQ field.
func (r *investmentLotWhereInputResolver) PriceNeq(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PriceNeq - priceNEQ"))
}

// PriceIn is the resolver for the priceIn field.
func (r *investmentLotWhereInputResolver) PriceIn(ctx context.Context, obj *ent.InvestmentLotWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: PriceIn - priceIn"))
}

// PriceNotIn is the resolver for the priceNotIn field.
func (r *investmentLotWhereInputResolver) PriceNotIn(ctx context.Context, obj *ent.InvestmentLotWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: PriceNotIn - priceNotIn"))
}

// PriceGt is the resolver for the priceGT field.
func (r *investmentLotWhereInputResolver) PriceGt(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PriceGt - priceGT"))
}

// PriceGte is the resolver for the priceGTE field.
func (r *investmentLotWhereInputResolver) PriceGte(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PriceGte - priceGTE"))
}

// PriceLt is the resolver for the priceLT field.
func (r *investmentLotWhereInputResolver) PriceLt(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PriceLt - priceLT"))
}

// PriceLte is the resolver for the priceLTE field.
func (r *investmentLotWhereInputResolver) PriceLte(ctx context.Context, obj *ent.InvestmentLotWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PriceLte - priceLTE"))
}

// Amount is the resolver for the amount field.
func (r *investmentWhereInputResolver) Amount(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Amount - amount"))
}

// AmountNeq is the resolver for the amountNEQ field.
func (r *investmentWhereInputResolver) AmountNeq(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountNeq - amountNEQ"))
}

// AmountIn is the resolver for the amountIn field.
func (r *investmentWhereInputResolver) AmountIn(ctx context.Context, obj *ent.InvestmentWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: AmountIn - amountIn"))
}

// AmountNotIn is the resolver for the amountNotIn field.
func (r *investmentWhereInputResolver) AmountNotIn(ctx context.Context, obj *ent.InvestmentWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: AmountNotIn - amountNotIn"))
}

// AmountGt is the resolver for the amountGT field.
func (r *investmentWhereInputResolver) AmountGt(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountGt - amountGT"))
}

// AmountGte is the resolver for the amountGTE field.
func (r *investmentWhereInputResolver) AmountGte(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountGte - amountGTE"))
}

// AmountLt is the resolver for the amountLT field.
func (r *investmentWhereInputResolver) AmountLt(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountLt - amountLT"))
}

// AmountLte is the resolver for the amountLTE field.
func (r *investmentWhereInputResolver) AmountLte(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountLte - amountLTE"))
}

// Quote is the resolver for the quote field.
func (r *investmentWhereInputResolver) Quote(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Quote - quote"))
}

// QuoteNeq is the resolver for the quoteNEQ field.
func (r *investmentWhereInputResolver) QuoteNeq(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: QuoteNeq - quoteNEQ"))
}

// QuoteIn is the resolver for the quoteIn field.
func (r *investmentWhereInputResolver) QuoteIn(ctx context.Context, obj *ent.InvestmentWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: QuoteIn - quoteIn"))
}

// QuoteNotIn is the resolver for the quoteNotIn field.
func (r *investmentWhereInputResolver) QuoteNotIn(ctx context.Context, obj *ent.InvestmentWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: QuoteNotIn - quoteNotIn"))
}

// QuoteGt is the resolver for the quoteGT field.
func (r *investmentWhereInputResolver) QuoteGt(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: QuoteGt - quoteGT"))
}

// QuoteGte is the resolver for the quoteGTE field.
func (r *investmentWhereInputResolver) QuoteGte(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: QuoteGte - quoteGTE"))
}

// QuoteLt is the resolver for the quoteLT field.
func (r *investmentWhereInputResolver) QuoteLt(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: QuoteLt - quoteLT"))
}

// QuoteLte is the resolver for the quoteLTE field.
func (r *investmentWhereInputResolver) QuoteLte(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: QuoteLte - quoteLTE"))
}

// Value is the resolver for the value field.
func (r *investmentWhereInputResolver) Value(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Value - value"))
}

// ValueNeq is the resolver for the valueNEQ field.
func (r *investmentWhereInputResolver) ValueNeq(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueNeq - valueNEQ"))
}

// ValueIn is the resolver for the valueIn field.
func (r *investmentWhereInputResolver) ValueIn(ctx context.Context, obj *ent.InvestmentWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: ValueIn - valueIn"))
}

// ValueNotIn is the resolver for the valueNotIn field.
func (r *investmentWhereInputResolver) ValueNotIn(ctx context.Context, obj *ent.InvestmentWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: ValueNotIn - valueNotIn"))
}

// ValueGt is the resolver for the valueGT field.
func (r *investmentWhereInputResolver) ValueGt(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueGt - valueGT"))
}

// ValueGte is the resolver for the valueGTE field.
func (r *investmentWhereInputResolver) ValueGte(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueGte - valueGTE"))
}

// ValueLt is the resolver for the valueLT field.
func (r *investmentWhereInputResolver) ValueLt(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueLt - valueLT"))
}

// ValueLte is the resolver for the valueLTE field.
func (r *investmentWhereInputResolver) ValueLte(ctx context.Context, obj *ent.InvestmentWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ValueLte - valueLTE"))
}

// Cost is the resolver for the cost field.
func (r *recurringSubscriptionWhereInputResolver) Cost(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Cost - cost"))
}

// CostNeq is the resolver for the costNEQ field.
func (r *recurringSubscriptionWhereInputResolver) CostNeq(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: CostNeq - costNEQ"))
}

// CostIn is the resolver for the costIn field.
func (r *recurringSubscriptionWhereInputResolver) CostIn(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: CostIn - costIn"))
}

// CostNotIn is the resolver for the costNotIn field.
func (r *recurringSubscriptionWhereInputResolver) CostNotIn(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: CostNotIn - costNotIn"))
}

// CostGt is the resolver for the costGT field.
func (r *recurringSubscriptionWhereInputResolver) CostGt(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: CostGt - costGT"))
}

// CostGte is the resolver for the costGTE field.
func (r *recurringSubscriptionWhereInputResolver) CostGte(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: CostGte - costGTE"))
}

// CostLt is the resolver for the costLT field.
func (r *recurringSubscriptionWhereInputResolver) CostLt(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: CostLt - costLT"))
}

// CostLte is the resolver for the costLTE field.
func (r *recurringSubscriptionWhereInputResolver) CostLte(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: CostLte - costLTE"))
}

// FxRate is the resolver for the fxRate field.
func (r *recurringSubscriptionWhereInputResolver) FxRate(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRate - fxRate"))
}

// FxRateNeq is the resolver for the fxRateNEQ field.
func (r *recurringSubscriptionWhereInputResolver) FxRateNeq(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateNeq - fxRateNEQ"))
}

// FxRateIn is the resolver for the fxRateIn field.
func (r *recurringSubscriptionWhereInputResolver) FxRateIn(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: FxRateIn - fxRateIn"))
}

// FxRateNotIn is the resolver for the fxRateNotIn field.
func (r *recurringSubscriptionWhereInputResolver) FxRateNotIn(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: FxRateNotIn - fxRateNotIn"))
}

// FxRateGt is the resolver for the fxRateGT field.
func (r *recurringSubscriptionWhereInputResolver) FxRateGt(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateGt - fxRateGT"))
}

// FxRateGte is the resolver for the fxRateGTE field.
func (r *recurringSubscriptionWhereInputResolver) FxRateGte(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateGte - fxRateGTE"))
}

// FxRateLt is the resolver for the fxRateLT field.
func (r *recurringSubscriptionWhereInputResolver) FxRateLt(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateLt - fxRateLT"))
}

// FxRateLte is the resolver for the fxRateLTE field.
func (r *recurringSubscriptionWhereInputResolver) FxRateLte(ctx context.Context, obj *ent.RecurringSubscriptionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: FxRateLte - fxRateLTE"))
}

// Amount is the resolver for the amount field.
func (r *transactionEntryWhereInputResolver) Amount(ctx context.Context, obj *ent.TransactionEntryWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Amount - amount"))
}

// AmountNeq is the resolver for the amountNEQ field.
func (r *transactionEntryWhereInputResolver) AmountNeq(ctx context.Context, obj *ent.TransactionEntryWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountNeq - amountNEQ"))
}

// AmountIn is the resolver for the amountIn field.
func (r *transactionEntryWhereInputResolver) AmountIn(ctx context.Context, obj *ent.TransactionEntryWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: AmountIn - amountIn"))
}

// AmountNotIn is the resolver for the amountNotIn field.
func (r *transactionEntryWhereInputResolver) AmountNotIn(ctx context.Context, obj *ent.TransactionEntryWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: AmountNotIn - amountNotIn"))
}

// AmountGt is the resolver for the amountGT field.
func (r *transactionEntryWhereInputResolver) AmountGt(ctx context.Context, obj *ent.TransactionEntryWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountGt - amountGT"))
}

// AmountGte is the resolver for the amountGTE field.
func (r *transactionEntryWhereInputResolver) AmountGte(ctx context.Context, obj *ent.TransactionEntryWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountGte - amountGTE"))
}

// AmountLt is the resolver for the amountLT field.
func (r *transactionEntryWhereInputResolver) AmountLt(ctx context.Context, obj *ent.TransactionEntryWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountLt - amountLT"))
}

// AmountLte is the resolver for the amountLTE field.
func (r *transactionEntryWhereInputResolver) AmountLte(ctx context.Context, obj *ent.TransactionEntryWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: AmountLte - amountLTE"))
}

// Amount is the resolver for the amount field.
func (r *updateInvestmentLotInputResolver) Amount(ctx context.Context, obj *ent.UpdateInvestmentLotInput, data *string) error {
	panic(fmt.Errorf("not implemented: Amount - amount"))
}

// Price is the resolver for the price field.
func (r *updateInvestmentLotInputResolver) Price(ctx context.Context, obj *ent.UpdateInvestmentLotInput, data *string) error {
	panic(fmt.Errorf("not implemented: Price - price"))
}

// Cost is the resolver for the cost field.
func (r *updateRecurringSubscriptionInputResolver) Cost(ctx context.Context, obj *ent.UpdateRecurringSubscriptionInput, data *string) error {
	if data == nil || *data == "" {
		return nil
	}

	dec, err := decimal.NewFromString(*data)
	if err != nil {
		return fmt.Errorf("invalid decimal string for cost: %v", err)
	}

	if dec.IsZero() {
		return fmt.Errorf("recurring subscription cost cannot be zero")
	}

	obj.Cost = &dec
	return nil
}

// Amount is the resolver for the amount field.
func (r *updateTransactionEntryInputResolver) Amount(ctx context.Context, obj *ent.UpdateTransactionEntryInput, data *string) error {
	panic(fmt.Errorf("not implemented: Amount - amount"))
}

// Account returns AccountResolver implementation.
func (r *Resolver) Account() AccountResolver { return &accountResolver{r} }

// Checkpoint returns CheckpointResolver implementation.
func (r *Resolver) Checkpoint() CheckpointResolver { return &checkpointResolver{r} }

// Household returns HouseholdResolver implementation.
func (r *Resolver) Household() HouseholdResolver { return &householdResolver{r} }

// Investment returns InvestmentResolver implementation.
func (r *Resolver) Investment() InvestmentResolver { return &investmentResolver{r} }

// InvestmentLot returns InvestmentLotResolver implementation.
func (r *Resolver) InvestmentLot() InvestmentLotResolver { return &investmentLotResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// RecurringSubscription returns RecurringSubscriptionResolver implementation.
func (r *Resolver) RecurringSubscription() RecurringSubscriptionResolver {
	return &recurringSubscriptionResolver{r}
}

// TransactionEntry returns TransactionEntryResolver implementation.
func (r *Resolver) TransactionEntry() TransactionEntryResolver { return &transactionEntryResolver{r} }

// AccountWhereInput returns AccountWhereInputResolver implementation.
func (r *Resolver) AccountWhereInput() AccountWhereInputResolver {
	return &accountWhereInputResolver{r}
}

// CheckpointWhereInput returns CheckpointWhereInputResolver implementation.
func (r *Resolver) CheckpointWhereInput() CheckpointWhereInputResolver {
	return &checkpointWhereInputResolver{r}
}

// CreateAccountInput returns CreateAccountInputResolver implementation.
func (r *Resolver) CreateAccountInput() CreateAccountInputResolver {
	return &createAccountInputResolver{r}
}

// CreateInvestmentInput returns CreateInvestmentInputResolver implementation.
func (r *Resolver) CreateInvestmentInput() CreateInvestmentInputResolver {
	return &createInvestmentInputResolver{r}
}

// CreateInvestmentLotInput returns CreateInvestmentLotInputResolver implementation.
func (r *Resolver) CreateInvestmentLotInput() CreateInvestmentLotInputResolver {
	return &createInvestmentLotInputResolver{r}
}

// CreateRecurringSubscriptionInput returns CreateRecurringSubscriptionInputResolver implementation.
func (r *Resolver) CreateRecurringSubscriptionInput() CreateRecurringSubscriptionInputResolver {
	return &createRecurringSubscriptionInputResolver{r}
}

// CreateTransactionEntryInput returns CreateTransactionEntryInputResolver implementation.
func (r *Resolver) CreateTransactionEntryInput() CreateTransactionEntryInputResolver {
	return &createTransactionEntryInputResolver{r}
}

// InvestmentLotWhereInput returns InvestmentLotWhereInputResolver implementation.
func (r *Resolver) InvestmentLotWhereInput() InvestmentLotWhereInputResolver {
	return &investmentLotWhereInputResolver{r}
}

// InvestmentWhereInput returns InvestmentWhereInputResolver implementation.
func (r *Resolver) InvestmentWhereInput() InvestmentWhereInputResolver {
	return &investmentWhereInputResolver{r}
}

// RecurringSubscriptionWhereInput returns RecurringSubscriptionWhereInputResolver implementation.
func (r *Resolver) RecurringSubscriptionWhereInput() RecurringSubscriptionWhereInputResolver {
	return &recurringSubscriptionWhereInputResolver{r}
}

// TransactionEntryWhereInput returns TransactionEntryWhereInputResolver implementation.
func (r *Resolver) TransactionEntryWhereInput() TransactionEntryWhereInputResolver {
	return &transactionEntryWhereInputResolver{r}
}

// UpdateInvestmentLotInput returns UpdateInvestmentLotInputResolver implementation.
func (r *Resolver) UpdateInvestmentLotInput() UpdateInvestmentLotInputResolver {
	return &updateInvestmentLotInputResolver{r}
}

// UpdateRecurringSubscriptionInput returns UpdateRecurringSubscriptionInputResolver implementation.
func (r *Resolver) UpdateRecurringSubscriptionInput() UpdateRecurringSubscriptionInputResolver {
	return &updateRecurringSubscriptionInputResolver{r}
}

// UpdateTransactionEntryInput returns UpdateTransactionEntryInputResolver implementation.
func (r *Resolver) UpdateTransactionEntryInput() UpdateTransactionEntryInputResolver {
	return &updateTransactionEntryInputResolver{r}
}

type accountResolver struct{ *Resolver }
type checkpointResolver struct{ *Resolver }
type householdResolver struct{ *Resolver }
type investmentResolver struct{ *Resolver }
type investmentLotResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type recurringSubscriptionResolver struct{ *Resolver }
type transactionEntryResolver struct{ *Resolver }
type accountWhereInputResolver struct{ *Resolver }
type checkpointWhereInputResolver struct{ *Resolver }
type createAccountInputResolver struct{ *Resolver }
type createInvestmentInputResolver struct{ *Resolver }
type createInvestmentLotInputResolver struct{ *Resolver }
type createRecurringSubscriptionInputResolver struct{ *Resolver }
type createTransactionEntryInputResolver struct{ *Resolver }
type investmentLotWhereInputResolver struct{ *Resolver }
type investmentWhereInputResolver struct{ *Resolver }
type recurringSubscriptionWhereInputResolver struct{ *Resolver }
type transactionEntryWhereInputResolver struct{ *Resolver }
type updateInvestmentLotInputResolver struct{ *Resolver }
type updateRecurringSubscriptionInputResolver struct{ *Resolver }
type updateTransactionEntryInputResolver struct{ *Resolver }
