package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"beavermoney.app/ent"
	"beavermoney.app/gql/model"
)

// FinancialReport is the resolver for the financialReport field.
func (r *householdResolver) FinancialReport(ctx context.Context, obj *ent.Household, period model.TimePeriodInput) (*model.FinancialReport, error) {
	// Parse time period
	start, end := parseTimePeriod(period)

	return &model.FinancialReport{
		StartDate: start,
		EndDate:   end,
	}, nil
}
