// Code generated by ent, DO NOT EDIT.

package snapshotentry

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the snapshotentry type in the database.
	Label = "snapshot_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHouseholdID holds the string denoting the household_id field in the database.
	FieldHouseholdID = "household_id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldLiquidity holds the string denoting the liquidity field in the database.
	FieldLiquidity = "liquidity"
	// FieldInvestment holds the string denoting the investment field in the database.
	FieldInvestment = "investment"
	// FieldProperty holds the string denoting the property field in the database.
	FieldProperty = "property"
	// FieldReceivable holds the string denoting the receivable field in the database.
	FieldReceivable = "receivable"
	// FieldLiability holds the string denoting the liability field in the database.
	FieldLiability = "liability"
	// FieldHouseholdCurrencyID holds the string denoting the household_currency_id field in the database.
	FieldHouseholdCurrencyID = "household_currency_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSnapshotID holds the string denoting the snapshot_id field in the database.
	FieldSnapshotID = "snapshot_id"
	// EdgeHousehold holds the string denoting the household edge name in mutations.
	EdgeHousehold = "household"
	// EdgeHouseholdCurrency holds the string denoting the household_currency edge name in mutations.
	EdgeHouseholdCurrency = "household_currency"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeSnapshot holds the string denoting the snapshot edge name in mutations.
	EdgeSnapshot = "snapshot"
	// Table holds the table name of the snapshotentry in the database.
	Table = "snapshot_entries"
	// HouseholdTable is the table that holds the household relation/edge.
	HouseholdTable = "snapshot_entries"
	// HouseholdInverseTable is the table name for the Household entity.
	// It exists in this package in order to avoid circular dependency with the "household" package.
	HouseholdInverseTable = "households"
	// HouseholdColumn is the table column denoting the household relation/edge.
	HouseholdColumn = "household_id"
	// HouseholdCurrencyTable is the table that holds the household_currency relation/edge.
	HouseholdCurrencyTable = "snapshot_entries"
	// HouseholdCurrencyInverseTable is the table name for the HouseholdCurrency entity.
	// It exists in this package in order to avoid circular dependency with the "householdcurrency" package.
	HouseholdCurrencyInverseTable = "household_currencies"
	// HouseholdCurrencyColumn is the table column denoting the household_currency relation/edge.
	HouseholdCurrencyColumn = "household_currency_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "snapshot_entries"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// SnapshotTable is the table that holds the snapshot relation/edge.
	SnapshotTable = "snapshot_entries"
	// SnapshotInverseTable is the table name for the Snapshot entity.
	// It exists in this package in order to avoid circular dependency with the "snapshot" package.
	SnapshotInverseTable = "snapshots"
	// SnapshotColumn is the table column denoting the snapshot relation/edge.
	SnapshotColumn = "snapshot_id"
)

// Columns holds all SQL columns for snapshotentry fields.
var Columns = []string{
	FieldID,
	FieldHouseholdID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldLiquidity,
	FieldInvestment,
	FieldProperty,
	FieldReceivable,
	FieldLiability,
	FieldHouseholdCurrencyID,
	FieldUserID,
	FieldSnapshotID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "beavermoney.app/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// HouseholdCurrencyIDValidator is a validator for the "household_currency_id" field. It is called by the builders before save.
	HouseholdCurrencyIDValidator func(int) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int) error
	// SnapshotIDValidator is a validator for the "snapshot_id" field. It is called by the builders before save.
	SnapshotIDValidator func(int) error
)

// OrderOption defines the ordering options for the SnapshotEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHouseholdID orders the results by the household_id field.
func ByHouseholdID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHouseholdID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByLiquidity orders the results by the liquidity field.
func ByLiquidity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLiquidity, opts...).ToFunc()
}

// ByInvestment orders the results by the investment field.
func ByInvestment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvestment, opts...).ToFunc()
}

// ByProperty orders the results by the property field.
func ByProperty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProperty, opts...).ToFunc()
}

// ByReceivable orders the results by the receivable field.
func ByReceivable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivable, opts...).ToFunc()
}

// ByLiability orders the results by the liability field.
func ByLiability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLiability, opts...).ToFunc()
}

// ByHouseholdCurrencyID orders the results by the household_currency_id field.
func ByHouseholdCurrencyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHouseholdCurrencyID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySnapshotID orders the results by the snapshot_id field.
func BySnapshotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotID, opts...).ToFunc()
}

// ByHouseholdField orders the results by household field.
func ByHouseholdField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHouseholdStep(), sql.OrderByField(field, opts...))
	}
}

// ByHouseholdCurrencyField orders the results by household_currency field.
func ByHouseholdCurrencyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHouseholdCurrencyStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// BySnapshotField orders the results by snapshot field.
func BySnapshotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSnapshotStep(), sql.OrderByField(field, opts...))
	}
}
func newHouseholdStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HouseholdInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HouseholdTable, HouseholdColumn),
	)
}
func newHouseholdCurrencyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HouseholdCurrencyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HouseholdCurrencyTable, HouseholdCurrencyColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newSnapshotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SnapshotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SnapshotTable, SnapshotColumn),
	)
}
