// Code generated by ent, DO NOT EDIT.

package snapshotrate

import (
	"time"

	"beavermoney.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldLTE(FieldID, id))
}

// HouseholdID applies equality check predicate on the "household_id" field. It's identical to HouseholdIDEQ.
func HouseholdID(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldHouseholdID, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldUpdateTime, v))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v decimal.Decimal) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldRate, v))
}

// SnapshotID applies equality check predicate on the "snapshot_id" field. It's identical to SnapshotIDEQ.
func SnapshotID(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldSnapshotID, v))
}

// FromHouseholdCurrencyID applies equality check predicate on the "from_household_currency_id" field. It's identical to FromHouseholdCurrencyIDEQ.
func FromHouseholdCurrencyID(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldFromHouseholdCurrencyID, v))
}

// ToHouseholdCurrencyID applies equality check predicate on the "to_household_currency_id" field. It's identical to ToHouseholdCurrencyIDEQ.
func ToHouseholdCurrencyID(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldToHouseholdCurrencyID, v))
}

// HouseholdIDEQ applies the EQ predicate on the "household_id" field.
func HouseholdIDEQ(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldHouseholdID, v))
}

// HouseholdIDNEQ applies the NEQ predicate on the "household_id" field.
func HouseholdIDNEQ(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNEQ(FieldHouseholdID, v))
}

// HouseholdIDIn applies the In predicate on the "household_id" field.
func HouseholdIDIn(vs ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldIn(FieldHouseholdID, vs...))
}

// HouseholdIDNotIn applies the NotIn predicate on the "household_id" field.
func HouseholdIDNotIn(vs ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNotIn(FieldHouseholdID, vs...))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldLTE(FieldUpdateTime, v))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v decimal.Decimal) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v decimal.Decimal) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...decimal.Decimal) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...decimal.Decimal) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v decimal.Decimal) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v decimal.Decimal) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v decimal.Decimal) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v decimal.Decimal) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldLTE(FieldRate, v))
}

// SnapshotIDEQ applies the EQ predicate on the "snapshot_id" field.
func SnapshotIDEQ(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldSnapshotID, v))
}

// SnapshotIDNEQ applies the NEQ predicate on the "snapshot_id" field.
func SnapshotIDNEQ(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNEQ(FieldSnapshotID, v))
}

// SnapshotIDIn applies the In predicate on the "snapshot_id" field.
func SnapshotIDIn(vs ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldIn(FieldSnapshotID, vs...))
}

// SnapshotIDNotIn applies the NotIn predicate on the "snapshot_id" field.
func SnapshotIDNotIn(vs ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNotIn(FieldSnapshotID, vs...))
}

// FromHouseholdCurrencyIDEQ applies the EQ predicate on the "from_household_currency_id" field.
func FromHouseholdCurrencyIDEQ(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldFromHouseholdCurrencyID, v))
}

// FromHouseholdCurrencyIDNEQ applies the NEQ predicate on the "from_household_currency_id" field.
func FromHouseholdCurrencyIDNEQ(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNEQ(FieldFromHouseholdCurrencyID, v))
}

// FromHouseholdCurrencyIDIn applies the In predicate on the "from_household_currency_id" field.
func FromHouseholdCurrencyIDIn(vs ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldIn(FieldFromHouseholdCurrencyID, vs...))
}

// FromHouseholdCurrencyIDNotIn applies the NotIn predicate on the "from_household_currency_id" field.
func FromHouseholdCurrencyIDNotIn(vs ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNotIn(FieldFromHouseholdCurrencyID, vs...))
}

// ToHouseholdCurrencyIDEQ applies the EQ predicate on the "to_household_currency_id" field.
func ToHouseholdCurrencyIDEQ(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldEQ(FieldToHouseholdCurrencyID, v))
}

// ToHouseholdCurrencyIDNEQ applies the NEQ predicate on the "to_household_currency_id" field.
func ToHouseholdCurrencyIDNEQ(v int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNEQ(FieldToHouseholdCurrencyID, v))
}

// ToHouseholdCurrencyIDIn applies the In predicate on the "to_household_currency_id" field.
func ToHouseholdCurrencyIDIn(vs ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldIn(FieldToHouseholdCurrencyID, vs...))
}

// ToHouseholdCurrencyIDNotIn applies the NotIn predicate on the "to_household_currency_id" field.
func ToHouseholdCurrencyIDNotIn(vs ...int) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.FieldNotIn(FieldToHouseholdCurrencyID, vs...))
}

// HasHousehold applies the HasEdge predicate on the "household" edge.
func HasHousehold() predicate.SnapshotRate {
	return predicate.SnapshotRate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, HouseholdTable, HouseholdColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHouseholdWith applies the HasEdge predicate on the "household" edge with a given conditions (other predicates).
func HasHouseholdWith(preds ...predicate.Household) predicate.SnapshotRate {
	return predicate.SnapshotRate(func(s *sql.Selector) {
		step := newHouseholdStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSnapshot applies the HasEdge predicate on the "snapshot" edge.
func HasSnapshot() predicate.SnapshotRate {
	return predicate.SnapshotRate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SnapshotTable, SnapshotColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotWith applies the HasEdge predicate on the "snapshot" edge with a given conditions (other predicates).
func HasSnapshotWith(preds ...predicate.Snapshot) predicate.SnapshotRate {
	return predicate.SnapshotRate(func(s *sql.Selector) {
		step := newSnapshotStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFromCurrency applies the HasEdge predicate on the "from_currency" edge.
func HasFromCurrency() predicate.SnapshotRate {
	return predicate.SnapshotRate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FromCurrencyTable, FromCurrencyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromCurrencyWith applies the HasEdge predicate on the "from_currency" edge with a given conditions (other predicates).
func HasFromCurrencyWith(preds ...predicate.HouseholdCurrency) predicate.SnapshotRate {
	return predicate.SnapshotRate(func(s *sql.Selector) {
		step := newFromCurrencyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasToCurrency applies the HasEdge predicate on the "to_currency" edge.
func HasToCurrency() predicate.SnapshotRate {
	return predicate.SnapshotRate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ToCurrencyTable, ToCurrencyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasToCurrencyWith applies the HasEdge predicate on the "to_currency" edge with a given conditions (other predicates).
func HasToCurrencyWith(preds ...predicate.HouseholdCurrency) predicate.SnapshotRate {
	return predicate.SnapshotRate(func(s *sql.Selector) {
		step := newToCurrencyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SnapshotRate) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SnapshotRate) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SnapshotRate) predicate.SnapshotRate {
	return predicate.SnapshotRate(sql.NotPredicates(p))
}
