// Code generated by ent, DO NOT EDIT.

package household

import (
	"time"

	"beavermoney.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldUpdateTime, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldName, v))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldLocale, v))
}

// CurrencyCode applies equality check predicate on the "currency_code" field. It's identical to CurrencyCodeEQ.
func CurrencyCode(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldCurrencyCode, v))
}

// LegacyCurrencyID applies equality check predicate on the "legacy_currency_id" field. It's identical to LegacyCurrencyIDEQ.
func LegacyCurrencyID(v int) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldLegacyCurrencyID, v))
}

// IsDemo applies equality check predicate on the "is_demo" field. It's identical to IsDemoEQ.
func IsDemo(v bool) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldIsDemo, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldUpdateTime, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Household {
	return predicate.Household(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Household {
	return predicate.Household(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Household {
	return predicate.Household(sql.FieldContainsFold(FieldName, v))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.Household {
	return predicate.Household(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.Household {
	return predicate.Household(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.Household {
	return predicate.Household(sql.FieldContainsFold(FieldLocale, v))
}

// CurrencyCodeEQ applies the EQ predicate on the "currency_code" field.
func CurrencyCodeEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldCurrencyCode, v))
}

// CurrencyCodeNEQ applies the NEQ predicate on the "currency_code" field.
func CurrencyCodeNEQ(v string) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldCurrencyCode, v))
}

// CurrencyCodeIn applies the In predicate on the "currency_code" field.
func CurrencyCodeIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldCurrencyCode, vs...))
}

// CurrencyCodeNotIn applies the NotIn predicate on the "currency_code" field.
func CurrencyCodeNotIn(vs ...string) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldCurrencyCode, vs...))
}

// CurrencyCodeGT applies the GT predicate on the "currency_code" field.
func CurrencyCodeGT(v string) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldCurrencyCode, v))
}

// CurrencyCodeGTE applies the GTE predicate on the "currency_code" field.
func CurrencyCodeGTE(v string) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldCurrencyCode, v))
}

// CurrencyCodeLT applies the LT predicate on the "currency_code" field.
func CurrencyCodeLT(v string) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldCurrencyCode, v))
}

// CurrencyCodeLTE applies the LTE predicate on the "currency_code" field.
func CurrencyCodeLTE(v string) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldCurrencyCode, v))
}

// CurrencyCodeContains applies the Contains predicate on the "currency_code" field.
func CurrencyCodeContains(v string) predicate.Household {
	return predicate.Household(sql.FieldContains(FieldCurrencyCode, v))
}

// CurrencyCodeHasPrefix applies the HasPrefix predicate on the "currency_code" field.
func CurrencyCodeHasPrefix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasPrefix(FieldCurrencyCode, v))
}

// CurrencyCodeHasSuffix applies the HasSuffix predicate on the "currency_code" field.
func CurrencyCodeHasSuffix(v string) predicate.Household {
	return predicate.Household(sql.FieldHasSuffix(FieldCurrencyCode, v))
}

// CurrencyCodeEqualFold applies the EqualFold predicate on the "currency_code" field.
func CurrencyCodeEqualFold(v string) predicate.Household {
	return predicate.Household(sql.FieldEqualFold(FieldCurrencyCode, v))
}

// CurrencyCodeContainsFold applies the ContainsFold predicate on the "currency_code" field.
func CurrencyCodeContainsFold(v string) predicate.Household {
	return predicate.Household(sql.FieldContainsFold(FieldCurrencyCode, v))
}

// LegacyCurrencyIDEQ applies the EQ predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDEQ(v int) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldLegacyCurrencyID, v))
}

// LegacyCurrencyIDNEQ applies the NEQ predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDNEQ(v int) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldLegacyCurrencyID, v))
}

// LegacyCurrencyIDIn applies the In predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDIn(vs ...int) predicate.Household {
	return predicate.Household(sql.FieldIn(FieldLegacyCurrencyID, vs...))
}

// LegacyCurrencyIDNotIn applies the NotIn predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDNotIn(vs ...int) predicate.Household {
	return predicate.Household(sql.FieldNotIn(FieldLegacyCurrencyID, vs...))
}

// LegacyCurrencyIDGT applies the GT predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDGT(v int) predicate.Household {
	return predicate.Household(sql.FieldGT(FieldLegacyCurrencyID, v))
}

// LegacyCurrencyIDGTE applies the GTE predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDGTE(v int) predicate.Household {
	return predicate.Household(sql.FieldGTE(FieldLegacyCurrencyID, v))
}

// LegacyCurrencyIDLT applies the LT predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDLT(v int) predicate.Household {
	return predicate.Household(sql.FieldLT(FieldLegacyCurrencyID, v))
}

// LegacyCurrencyIDLTE applies the LTE predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDLTE(v int) predicate.Household {
	return predicate.Household(sql.FieldLTE(FieldLegacyCurrencyID, v))
}

// LegacyCurrencyIDIsNil applies the IsNil predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDIsNil() predicate.Household {
	return predicate.Household(sql.FieldIsNull(FieldLegacyCurrencyID))
}

// LegacyCurrencyIDNotNil applies the NotNil predicate on the "legacy_currency_id" field.
func LegacyCurrencyIDNotNil() predicate.Household {
	return predicate.Household(sql.FieldNotNull(FieldLegacyCurrencyID))
}

// IsDemoEQ applies the EQ predicate on the "is_demo" field.
func IsDemoEQ(v bool) predicate.Household {
	return predicate.Household(sql.FieldEQ(FieldIsDemo, v))
}

// IsDemoNEQ applies the NEQ predicate on the "is_demo" field.
func IsDemoNEQ(v bool) predicate.Household {
	return predicate.Household(sql.FieldNEQ(FieldIsDemo, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, UsersTable, UsersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransactions applies the HasEdge predicate on the "transactions" edge.
func HasTransactions() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransactionsTable, TransactionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionsWith applies the HasEdge predicate on the "transactions" edge with a given conditions (other predicates).
func HasTransactionsWith(preds ...predicate.Transaction) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newTransactionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvestments applies the HasEdge predicate on the "investments" edge.
func HasInvestments() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InvestmentsTable, InvestmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvestmentsWith applies the HasEdge predicate on the "investments" edge with a given conditions (other predicates).
func HasInvestmentsWith(preds ...predicate.Investment) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newInvestmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvestmentLots applies the HasEdge predicate on the "investment_lots" edge.
func HasInvestmentLots() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InvestmentLotsTable, InvestmentLotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvestmentLotsWith applies the HasEdge predicate on the "investment_lots" edge with a given conditions (other predicates).
func HasInvestmentLotsWith(preds ...predicate.InvestmentLot) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newInvestmentLotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransactionCategories applies the HasEdge predicate on the "transaction_categories" edge.
func HasTransactionCategories() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransactionCategoriesTable, TransactionCategoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionCategoriesWith applies the HasEdge predicate on the "transaction_categories" edge with a given conditions (other predicates).
func HasTransactionCategoriesWith(preds ...predicate.TransactionCategory) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newTransactionCategoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransactionEntries applies the HasEdge predicate on the "transaction_entries" edge.
func HasTransactionEntries() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransactionEntriesTable, TransactionEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionEntriesWith applies the HasEdge predicate on the "transaction_entries" edge with a given conditions (other predicates).
func HasTransactionEntriesWith(preds ...predicate.TransactionEntry) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newTransactionEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecurringSubscriptions applies the HasEdge predicate on the "recurring_subscriptions" edge.
func HasRecurringSubscriptions() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecurringSubscriptionsTable, RecurringSubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecurringSubscriptionsWith applies the HasEdge predicate on the "recurring_subscriptions" edge with a given conditions (other predicates).
func HasRecurringSubscriptionsWith(preds ...predicate.RecurringSubscription) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newRecurringSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSnapshots applies the HasEdge predicate on the "snapshots" edge.
func HasSnapshots() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotsWith applies the HasEdge predicate on the "snapshots" edge with a given conditions (other predicates).
func HasSnapshotsWith(preds ...predicate.Snapshot) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSnapshotEntries applies the HasEdge predicate on the "snapshot_entries" edge.
func HasSnapshotEntries() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SnapshotEntriesTable, SnapshotEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotEntriesWith applies the HasEdge predicate on the "snapshot_entries" edge with a given conditions (other predicates).
func HasSnapshotEntriesWith(preds ...predicate.SnapshotEntry) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newSnapshotEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHouseholdCurrencies applies the HasEdge predicate on the "household_currencies" edge.
func HasHouseholdCurrencies() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HouseholdCurrenciesTable, HouseholdCurrenciesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHouseholdCurrenciesWith applies the HasEdge predicate on the "household_currencies" edge with a given conditions (other predicates).
func HasHouseholdCurrenciesWith(preds ...predicate.HouseholdCurrency) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newHouseholdCurrenciesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHouseholdRates applies the HasEdge predicate on the "household_rates" edge.
func HasHouseholdRates() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HouseholdRatesTable, HouseholdRatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHouseholdRatesWith applies the HasEdge predicate on the "household_rates" edge with a given conditions (other predicates).
func HasHouseholdRatesWith(preds ...predicate.HouseholdRate) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newHouseholdRatesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserHouseholds applies the HasEdge predicate on the "user_households" edge.
func HasUserHouseholds() predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, UserHouseholdsTable, UserHouseholdsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserHouseholdsWith applies the HasEdge predicate on the "user_households" edge with a given conditions (other predicates).
func HasUserHouseholdsWith(preds ...predicate.UserHousehold) predicate.Household {
	return predicate.Household(func(s *sql.Selector) {
		step := newUserHouseholdsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Household) predicate.Household {
	return predicate.Household(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Household) predicate.Household {
	return predicate.Household(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Household) predicate.Household {
	return predicate.Household(sql.NotPredicates(p))
}
