// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"beavermoney.app/ent/checkpoint"
	"beavermoney.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CheckpointUpdate is the builder for updating Checkpoint entities.
type CheckpointUpdate struct {
	config
	hooks     []Hook
	mutation  *CheckpointMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CheckpointUpdate builder.
func (_u *CheckpointUpdate) Where(ps ...predicate.Checkpoint) *CheckpointUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *CheckpointUpdate) SetUpdateTime(v time.Time) *CheckpointUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *CheckpointUpdate) SetNote(v string) *CheckpointUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *CheckpointUpdate) SetNillableNote(v *string) *CheckpointUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *CheckpointUpdate) ClearNote() *CheckpointUpdate {
	_u.mutation.ClearNote()
	return _u
}

// Mutation returns the CheckpointMutation object of the builder.
func (_u *CheckpointUpdate) Mutation() *CheckpointMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckpointUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckpointUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckpointUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckpointUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CheckpointUpdate) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if checkpoint.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized checkpoint.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := checkpoint.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckpointUpdate) check() error {
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Checkpoint.household"`)
	}
	if _u.mutation.CurrencyCleared() && len(_u.mutation.CurrencyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Checkpoint.currency"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CheckpointUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CheckpointUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CheckpointUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkpoint.Table, checkpoint.Columns, sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(checkpoint.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(checkpoint.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(checkpoint.FieldNote, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckpointUpdateOne is the builder for updating a single Checkpoint entity.
type CheckpointUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CheckpointMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *CheckpointUpdateOne) SetUpdateTime(v time.Time) *CheckpointUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *CheckpointUpdateOne) SetNote(v string) *CheckpointUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *CheckpointUpdateOne) SetNillableNote(v *string) *CheckpointUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *CheckpointUpdateOne) ClearNote() *CheckpointUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// Mutation returns the CheckpointMutation object of the builder.
func (_u *CheckpointUpdateOne) Mutation() *CheckpointMutation {
	return _u.mutation
}

// Where appends a list predicates to the CheckpointUpdate builder.
func (_u *CheckpointUpdateOne) Where(ps ...predicate.Checkpoint) *CheckpointUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckpointUpdateOne) Select(field string, fields ...string) *CheckpointUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Checkpoint entity.
func (_u *CheckpointUpdateOne) Save(ctx context.Context) (*Checkpoint, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckpointUpdateOne) SaveX(ctx context.Context) *Checkpoint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckpointUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckpointUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CheckpointUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if checkpoint.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized checkpoint.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := checkpoint.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckpointUpdateOne) check() error {
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Checkpoint.household"`)
	}
	if _u.mutation.CurrencyCleared() && len(_u.mutation.CurrencyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Checkpoint.currency"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CheckpointUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CheckpointUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CheckpointUpdateOne) sqlSave(ctx context.Context) (_node *Checkpoint, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkpoint.Table, checkpoint.Columns, sqlgraph.NewFieldSpec(checkpoint.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Checkpoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkpoint.FieldID)
		for _, f := range fields {
			if !checkpoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(checkpoint.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(checkpoint.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(checkpoint.FieldNote, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Checkpoint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
