// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Account) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *Account) HouseholdCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.HouseholdCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdCurrency().Only(ctx)
	}
	return result, err
}

func (_m *Account) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *Account) TransactionEntries(ctx context.Context) (result []*TransactionEntry, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedTransactionEntries(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.TransactionEntriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryTransactionEntries().All(ctx)
	}
	return result, err
}

func (_m *Account) Investments(ctx context.Context) (result []*Investment, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedInvestments(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.InvestmentsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryInvestments().All(ctx)
	}
	return result, err
}

func (_m *Household) Users(ctx context.Context) (result []*User, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedUsers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.UsersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryUsers().All(ctx)
	}
	return result, err
}

func (_m *Household) Accounts(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, where *AccountWhereInput,
) (*AccountConnection, error) {
	opts := []AccountPaginateOption{
		WithAccountFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[1][alias]
	if nodes, err := _m.NamedAccounts(alias); err == nil || hasTotalCount {
		pager, err := newAccountPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &AccountConnection{Edges: []*AccountEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryAccounts().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Household) Transactions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *TransactionOrder, where *TransactionWhereInput,
) (*TransactionConnection, error) {
	opts := []TransactionPaginateOption{
		WithTransactionOrder(orderBy),
		WithTransactionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[2][alias]
	if nodes, err := _m.NamedTransactions(alias); err == nil || hasTotalCount {
		pager, err := newTransactionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &TransactionConnection{Edges: []*TransactionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryTransactions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Household) Investments(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, where *InvestmentWhereInput,
) (*InvestmentConnection, error) {
	opts := []InvestmentPaginateOption{
		WithInvestmentFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[3][alias]
	if nodes, err := _m.NamedInvestments(alias); err == nil || hasTotalCount {
		pager, err := newInvestmentPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &InvestmentConnection{Edges: []*InvestmentEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryInvestments().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Household) InvestmentLots(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, where *InvestmentLotWhereInput,
) (*InvestmentLotConnection, error) {
	opts := []InvestmentLotPaginateOption{
		WithInvestmentLotFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[4][alias]
	if nodes, err := _m.NamedInvestmentLots(alias); err == nil || hasTotalCount {
		pager, err := newInvestmentLotPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &InvestmentLotConnection{Edges: []*InvestmentLotEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryInvestmentLots().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Household) TransactionCategories(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, where *TransactionCategoryWhereInput,
) (*TransactionCategoryConnection, error) {
	opts := []TransactionCategoryPaginateOption{
		WithTransactionCategoryFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[5][alias]
	if nodes, err := _m.NamedTransactionCategories(alias); err == nil || hasTotalCount {
		pager, err := newTransactionCategoryPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &TransactionCategoryConnection{Edges: []*TransactionCategoryEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryTransactionCategories().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Household) TransactionEntries(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, where *TransactionEntryWhereInput,
) (*TransactionEntryConnection, error) {
	opts := []TransactionEntryPaginateOption{
		WithTransactionEntryFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[6][alias]
	if nodes, err := _m.NamedTransactionEntries(alias); err == nil || hasTotalCount {
		pager, err := newTransactionEntryPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &TransactionEntryConnection{Edges: []*TransactionEntryEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryTransactionEntries().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Household) RecurringSubscriptions(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, where *RecurringSubscriptionWhereInput,
) (*RecurringSubscriptionConnection, error) {
	opts := []RecurringSubscriptionPaginateOption{
		WithRecurringSubscriptionFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[7][alias]
	if nodes, err := _m.NamedRecurringSubscriptions(alias); err == nil || hasTotalCount {
		pager, err := newRecurringSubscriptionPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &RecurringSubscriptionConnection{Edges: []*RecurringSubscriptionEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QueryRecurringSubscriptions().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Household) Snapshots(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, where *SnapshotWhereInput,
) (*SnapshotConnection, error) {
	opts := []SnapshotPaginateOption{
		WithSnapshotFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[8][alias]
	if nodes, err := _m.NamedSnapshots(alias); err == nil || hasTotalCount {
		pager, err := newSnapshotPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &SnapshotConnection{Edges: []*SnapshotEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QuerySnapshots().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Household) SnapshotEntries(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, where *SnapshotEntryWhereInput,
) (*SnapshotEntryConnection, error) {
	opts := []SnapshotEntryPaginateOption{
		WithSnapshotEntryFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := _m.Edges.totalCount[9][alias]
	if nodes, err := _m.NamedSnapshotEntries(alias); err == nil || hasTotalCount {
		pager, err := newSnapshotEntryPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &SnapshotEntryConnection{Edges: []*SnapshotEntryEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return _m.QuerySnapshotEntries().Paginate(ctx, after, first, before, last, opts...)
}

func (_m *Household) HouseholdCurrencies(ctx context.Context) (result []*HouseholdCurrency, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHouseholdCurrencies(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HouseholdCurrenciesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdCurrencies().All(ctx)
	}
	return result, err
}

func (_m *Household) HouseholdRates(ctx context.Context) (result []*HouseholdRate, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHouseholdRates(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HouseholdRatesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdRates().All(ctx)
	}
	return result, err
}

func (_m *Household) UserHouseholds(ctx context.Context) (result []*UserHousehold, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedUserHouseholds(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.UserHouseholdsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryUserHouseholds().All(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) Accounts(ctx context.Context) (result []*Account, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedAccounts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.AccountsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryAccounts().All(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) Investments(ctx context.Context) (result []*Investment, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedInvestments(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.InvestmentsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryInvestments().All(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) TransactionEntries(ctx context.Context) (result []*TransactionEntry, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedTransactionEntries(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.TransactionEntriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryTransactionEntries().All(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) RecurringSubscriptions(ctx context.Context) (result []*RecurringSubscription, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedRecurringSubscriptions(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.RecurringSubscriptionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryRecurringSubscriptions().All(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) SnapshotEntries(ctx context.Context) (result []*SnapshotEntry, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSnapshotEntries(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SnapshotEntriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySnapshotEntries().All(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) SnapshotRatesFrom(ctx context.Context) (result []*SnapshotRate, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSnapshotRatesFrom(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SnapshotRatesFromOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySnapshotRatesFrom().All(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) SnapshotRatesTo(ctx context.Context) (result []*SnapshotRate, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSnapshotRatesTo(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SnapshotRatesToOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySnapshotRatesTo().All(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) HouseholdRatesFrom(ctx context.Context) (result []*HouseholdRate, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHouseholdRatesFrom(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HouseholdRatesFromOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdRatesFrom().All(ctx)
	}
	return result, err
}

func (_m *HouseholdCurrency) HouseholdRatesTo(ctx context.Context) (result []*HouseholdRate, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHouseholdRatesTo(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HouseholdRatesToOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdRatesTo().All(ctx)
	}
	return result, err
}

func (_m *HouseholdRate) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *HouseholdRate) FromCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.FromCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryFromCurrency().Only(ctx)
	}
	return result, err
}

func (_m *HouseholdRate) ToCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.ToCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryToCurrency().Only(ctx)
	}
	return result, err
}

func (_m *Investment) Account(ctx context.Context) (*Account, error) {
	result, err := _m.Edges.AccountOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAccount().Only(ctx)
	}
	return result, err
}

func (_m *Investment) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *Investment) HouseholdCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.HouseholdCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdCurrency().Only(ctx)
	}
	return result, err
}

func (_m *Investment) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *Investment) InvestmentLots(ctx context.Context) (result []*InvestmentLot, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedInvestmentLots(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.InvestmentLotsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryInvestmentLots().All(ctx)
	}
	return result, err
}

func (_m *InvestmentLot) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *InvestmentLot) Investment(ctx context.Context) (*Investment, error) {
	result, err := _m.Edges.InvestmentOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryInvestment().Only(ctx)
	}
	return result, err
}

func (_m *InvestmentLot) Transaction(ctx context.Context) (*Transaction, error) {
	result, err := _m.Edges.TransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryTransaction().Only(ctx)
	}
	return result, err
}

func (_m *RecurringSubscription) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *RecurringSubscription) HouseholdCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.HouseholdCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdCurrency().Only(ctx)
	}
	return result, err
}

func (_m *RecurringSubscription) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *Snapshot) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *Snapshot) SnapshotEntries(ctx context.Context) (result []*SnapshotEntry, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSnapshotEntries(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SnapshotEntriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySnapshotEntries().All(ctx)
	}
	return result, err
}

func (_m *Snapshot) SnapshotRates(ctx context.Context) (result []*SnapshotRate, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSnapshotRates(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SnapshotRatesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySnapshotRates().All(ctx)
	}
	return result, err
}

func (_m *SnapshotEntry) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *SnapshotEntry) HouseholdCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.HouseholdCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdCurrency().Only(ctx)
	}
	return result, err
}

func (_m *SnapshotEntry) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *SnapshotEntry) Snapshot(ctx context.Context) (*Snapshot, error) {
	result, err := _m.Edges.SnapshotOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySnapshot().Only(ctx)
	}
	return result, err
}

func (_m *SnapshotRate) Snapshot(ctx context.Context) (*Snapshot, error) {
	result, err := _m.Edges.SnapshotOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySnapshot().Only(ctx)
	}
	return result, err
}

func (_m *SnapshotRate) FromCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.FromCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryFromCurrency().Only(ctx)
	}
	return result, err
}

func (_m *SnapshotRate) ToCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.ToCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryToCurrency().Only(ctx)
	}
	return result, err
}

func (_m *Transaction) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *Transaction) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *Transaction) Category(ctx context.Context) (*TransactionCategory, error) {
	result, err := _m.Edges.CategoryOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryCategory().Only(ctx)
	}
	return result, err
}

func (_m *Transaction) TransactionEntries(ctx context.Context) (result []*TransactionEntry, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedTransactionEntries(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.TransactionEntriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryTransactionEntries().All(ctx)
	}
	return result, err
}

func (_m *Transaction) InvestmentLots(ctx context.Context) (result []*InvestmentLot, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedInvestmentLots(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.InvestmentLotsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryInvestmentLots().All(ctx)
	}
	return result, err
}

func (_m *TransactionCategory) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *TransactionCategory) Transactions(ctx context.Context) (result []*Transaction, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedTransactions(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.TransactionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryTransactions().All(ctx)
	}
	return result, err
}

func (_m *TransactionEntry) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *TransactionEntry) Account(ctx context.Context) (*Account, error) {
	result, err := _m.Edges.AccountOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAccount().Only(ctx)
	}
	return result, err
}

func (_m *TransactionEntry) HouseholdCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.HouseholdCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdCurrency().Only(ctx)
	}
	return result, err
}

func (_m *TransactionEntry) Transaction(ctx context.Context) (*Transaction, error) {
	result, err := _m.Edges.TransactionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryTransaction().Only(ctx)
	}
	return result, err
}

func (_m *User) Households(ctx context.Context) (result []*Household, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHouseholds(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HouseholdsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholds().All(ctx)
	}
	return result, err
}

func (_m *User) Accounts(ctx context.Context) (result []*Account, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedAccounts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.AccountsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryAccounts().All(ctx)
	}
	return result, err
}

func (_m *User) Investments(ctx context.Context) (result []*Investment, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedInvestments(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.InvestmentsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryInvestments().All(ctx)
	}
	return result, err
}

func (_m *User) Transactions(ctx context.Context) (result []*Transaction, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedTransactions(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.TransactionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryTransactions().All(ctx)
	}
	return result, err
}

func (_m *User) UserKeys(ctx context.Context) (result []*UserKey, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedUserKeys(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.UserKeysOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryUserKeys().All(ctx)
	}
	return result, err
}

func (_m *User) RecurringSubscriptions(ctx context.Context) (result []*RecurringSubscription, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedRecurringSubscriptions(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.RecurringSubscriptionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryRecurringSubscriptions().All(ctx)
	}
	return result, err
}

func (_m *User) SnapshotEntries(ctx context.Context) (result []*SnapshotEntry, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSnapshotEntries(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SnapshotEntriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySnapshotEntries().All(ctx)
	}
	return result, err
}

func (_m *User) UserHouseholds(ctx context.Context) (result []*UserHousehold, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedUserHouseholds(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.UserHouseholdsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryUserHouseholds().All(ctx)
	}
	return result, err
}

func (_m *UserHousehold) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *UserHousehold) Household(ctx context.Context) (*Household, error) {
	result, err := _m.Edges.HouseholdOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHousehold().Only(ctx)
	}
	return result, err
}

func (_m *UserHousehold) HouseholdCurrency(ctx context.Context) (*HouseholdCurrency, error) {
	result, err := _m.Edges.HouseholdCurrencyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHouseholdCurrency().Only(ctx)
	}
	return result, err
}

func (_m *UserKey) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}
