// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"beavermoney.app/ent/account"
	"beavermoney.app/ent/householdcurrency"
	"beavermoney.app/ent/householdrate"
	"beavermoney.app/ent/investment"
	"beavermoney.app/ent/predicate"
	"beavermoney.app/ent/recurringsubscription"
	"beavermoney.app/ent/snapshotentry"
	"beavermoney.app/ent/snapshotrate"
	"beavermoney.app/ent/transactionentry"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HouseholdCurrencyUpdate is the builder for updating HouseholdCurrency entities.
type HouseholdCurrencyUpdate struct {
	config
	hooks     []Hook
	mutation  *HouseholdCurrencyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the HouseholdCurrencyUpdate builder.
func (_u *HouseholdCurrencyUpdate) Where(ps ...predicate.HouseholdCurrency) *HouseholdCurrencyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *HouseholdCurrencyUpdate) SetUpdateTime(v time.Time) *HouseholdCurrencyUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetImportant sets the "important" field.
func (_u *HouseholdCurrencyUpdate) SetImportant(v bool) *HouseholdCurrencyUpdate {
	_u.mutation.SetImportant(v)
	return _u
}

// SetNillableImportant sets the "important" field if the given value is not nil.
func (_u *HouseholdCurrencyUpdate) SetNillableImportant(v *bool) *HouseholdCurrencyUpdate {
	if v != nil {
		_u.SetImportant(*v)
	}
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *HouseholdCurrencyUpdate) AddAccountIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *HouseholdCurrencyUpdate) AddAccounts(v ...*Account) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddInvestmentIDs adds the "investments" edge to the Investment entity by IDs.
func (_u *HouseholdCurrencyUpdate) AddInvestmentIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.AddInvestmentIDs(ids...)
	return _u
}

// AddInvestments adds the "investments" edges to the Investment entity.
func (_u *HouseholdCurrencyUpdate) AddInvestments(v ...*Investment) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvestmentIDs(ids...)
}

// AddTransactionEntryIDs adds the "transaction_entries" edge to the TransactionEntry entity by IDs.
func (_u *HouseholdCurrencyUpdate) AddTransactionEntryIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.AddTransactionEntryIDs(ids...)
	return _u
}

// AddTransactionEntries adds the "transaction_entries" edges to the TransactionEntry entity.
func (_u *HouseholdCurrencyUpdate) AddTransactionEntries(v ...*TransactionEntry) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionEntryIDs(ids...)
}

// AddRecurringSubscriptionIDs adds the "recurring_subscriptions" edge to the RecurringSubscription entity by IDs.
func (_u *HouseholdCurrencyUpdate) AddRecurringSubscriptionIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.AddRecurringSubscriptionIDs(ids...)
	return _u
}

// AddRecurringSubscriptions adds the "recurring_subscriptions" edges to the RecurringSubscription entity.
func (_u *HouseholdCurrencyUpdate) AddRecurringSubscriptions(v ...*RecurringSubscription) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecurringSubscriptionIDs(ids...)
}

// AddSnapshotEntryIDs adds the "snapshot_entries" edge to the SnapshotEntry entity by IDs.
func (_u *HouseholdCurrencyUpdate) AddSnapshotEntryIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.AddSnapshotEntryIDs(ids...)
	return _u
}

// AddSnapshotEntries adds the "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *HouseholdCurrencyUpdate) AddSnapshotEntries(v ...*SnapshotEntry) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotEntryIDs(ids...)
}

// AddSnapshotRatesFromIDs adds the "snapshot_rates_from" edge to the SnapshotRate entity by IDs.
func (_u *HouseholdCurrencyUpdate) AddSnapshotRatesFromIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.AddSnapshotRatesFromIDs(ids...)
	return _u
}

// AddSnapshotRatesFrom adds the "snapshot_rates_from" edges to the SnapshotRate entity.
func (_u *HouseholdCurrencyUpdate) AddSnapshotRatesFrom(v ...*SnapshotRate) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotRatesFromIDs(ids...)
}

// AddSnapshotRatesToIDs adds the "snapshot_rates_to" edge to the SnapshotRate entity by IDs.
func (_u *HouseholdCurrencyUpdate) AddSnapshotRatesToIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.AddSnapshotRatesToIDs(ids...)
	return _u
}

// AddSnapshotRatesTo adds the "snapshot_rates_to" edges to the SnapshotRate entity.
func (_u *HouseholdCurrencyUpdate) AddSnapshotRatesTo(v ...*SnapshotRate) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotRatesToIDs(ids...)
}

// AddHouseholdRatesFromIDs adds the "household_rates_from" edge to the HouseholdRate entity by IDs.
func (_u *HouseholdCurrencyUpdate) AddHouseholdRatesFromIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.AddHouseholdRatesFromIDs(ids...)
	return _u
}

// AddHouseholdRatesFrom adds the "household_rates_from" edges to the HouseholdRate entity.
func (_u *HouseholdCurrencyUpdate) AddHouseholdRatesFrom(v ...*HouseholdRate) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHouseholdRatesFromIDs(ids...)
}

// AddHouseholdRatesToIDs adds the "household_rates_to" edge to the HouseholdRate entity by IDs.
func (_u *HouseholdCurrencyUpdate) AddHouseholdRatesToIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.AddHouseholdRatesToIDs(ids...)
	return _u
}

// AddHouseholdRatesTo adds the "household_rates_to" edges to the HouseholdRate entity.
func (_u *HouseholdCurrencyUpdate) AddHouseholdRatesTo(v ...*HouseholdRate) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHouseholdRatesToIDs(ids...)
}

// Mutation returns the HouseholdCurrencyMutation object of the builder.
func (_u *HouseholdCurrencyUpdate) Mutation() *HouseholdCurrencyMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *HouseholdCurrencyUpdate) ClearAccounts() *HouseholdCurrencyUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *HouseholdCurrencyUpdate) RemoveAccountIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *HouseholdCurrencyUpdate) RemoveAccounts(v ...*Account) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearInvestments clears all "investments" edges to the Investment entity.
func (_u *HouseholdCurrencyUpdate) ClearInvestments() *HouseholdCurrencyUpdate {
	_u.mutation.ClearInvestments()
	return _u
}

// RemoveInvestmentIDs removes the "investments" edge to Investment entities by IDs.
func (_u *HouseholdCurrencyUpdate) RemoveInvestmentIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.RemoveInvestmentIDs(ids...)
	return _u
}

// RemoveInvestments removes "investments" edges to Investment entities.
func (_u *HouseholdCurrencyUpdate) RemoveInvestments(v ...*Investment) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvestmentIDs(ids...)
}

// ClearTransactionEntries clears all "transaction_entries" edges to the TransactionEntry entity.
func (_u *HouseholdCurrencyUpdate) ClearTransactionEntries() *HouseholdCurrencyUpdate {
	_u.mutation.ClearTransactionEntries()
	return _u
}

// RemoveTransactionEntryIDs removes the "transaction_entries" edge to TransactionEntry entities by IDs.
func (_u *HouseholdCurrencyUpdate) RemoveTransactionEntryIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.RemoveTransactionEntryIDs(ids...)
	return _u
}

// RemoveTransactionEntries removes "transaction_entries" edges to TransactionEntry entities.
func (_u *HouseholdCurrencyUpdate) RemoveTransactionEntries(v ...*TransactionEntry) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionEntryIDs(ids...)
}

// ClearRecurringSubscriptions clears all "recurring_subscriptions" edges to the RecurringSubscription entity.
func (_u *HouseholdCurrencyUpdate) ClearRecurringSubscriptions() *HouseholdCurrencyUpdate {
	_u.mutation.ClearRecurringSubscriptions()
	return _u
}

// RemoveRecurringSubscriptionIDs removes the "recurring_subscriptions" edge to RecurringSubscription entities by IDs.
func (_u *HouseholdCurrencyUpdate) RemoveRecurringSubscriptionIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.RemoveRecurringSubscriptionIDs(ids...)
	return _u
}

// RemoveRecurringSubscriptions removes "recurring_subscriptions" edges to RecurringSubscription entities.
func (_u *HouseholdCurrencyUpdate) RemoveRecurringSubscriptions(v ...*RecurringSubscription) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecurringSubscriptionIDs(ids...)
}

// ClearSnapshotEntries clears all "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *HouseholdCurrencyUpdate) ClearSnapshotEntries() *HouseholdCurrencyUpdate {
	_u.mutation.ClearSnapshotEntries()
	return _u
}

// RemoveSnapshotEntryIDs removes the "snapshot_entries" edge to SnapshotEntry entities by IDs.
func (_u *HouseholdCurrencyUpdate) RemoveSnapshotEntryIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.RemoveSnapshotEntryIDs(ids...)
	return _u
}

// RemoveSnapshotEntries removes "snapshot_entries" edges to SnapshotEntry entities.
func (_u *HouseholdCurrencyUpdate) RemoveSnapshotEntries(v ...*SnapshotEntry) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotEntryIDs(ids...)
}

// ClearSnapshotRatesFrom clears all "snapshot_rates_from" edges to the SnapshotRate entity.
func (_u *HouseholdCurrencyUpdate) ClearSnapshotRatesFrom() *HouseholdCurrencyUpdate {
	_u.mutation.ClearSnapshotRatesFrom()
	return _u
}

// RemoveSnapshotRatesFromIDs removes the "snapshot_rates_from" edge to SnapshotRate entities by IDs.
func (_u *HouseholdCurrencyUpdate) RemoveSnapshotRatesFromIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.RemoveSnapshotRatesFromIDs(ids...)
	return _u
}

// RemoveSnapshotRatesFrom removes "snapshot_rates_from" edges to SnapshotRate entities.
func (_u *HouseholdCurrencyUpdate) RemoveSnapshotRatesFrom(v ...*SnapshotRate) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotRatesFromIDs(ids...)
}

// ClearSnapshotRatesTo clears all "snapshot_rates_to" edges to the SnapshotRate entity.
func (_u *HouseholdCurrencyUpdate) ClearSnapshotRatesTo() *HouseholdCurrencyUpdate {
	_u.mutation.ClearSnapshotRatesTo()
	return _u
}

// RemoveSnapshotRatesToIDs removes the "snapshot_rates_to" edge to SnapshotRate entities by IDs.
func (_u *HouseholdCurrencyUpdate) RemoveSnapshotRatesToIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.RemoveSnapshotRatesToIDs(ids...)
	return _u
}

// RemoveSnapshotRatesTo removes "snapshot_rates_to" edges to SnapshotRate entities.
func (_u *HouseholdCurrencyUpdate) RemoveSnapshotRatesTo(v ...*SnapshotRate) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotRatesToIDs(ids...)
}

// ClearHouseholdRatesFrom clears all "household_rates_from" edges to the HouseholdRate entity.
func (_u *HouseholdCurrencyUpdate) ClearHouseholdRatesFrom() *HouseholdCurrencyUpdate {
	_u.mutation.ClearHouseholdRatesFrom()
	return _u
}

// RemoveHouseholdRatesFromIDs removes the "household_rates_from" edge to HouseholdRate entities by IDs.
func (_u *HouseholdCurrencyUpdate) RemoveHouseholdRatesFromIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.RemoveHouseholdRatesFromIDs(ids...)
	return _u
}

// RemoveHouseholdRatesFrom removes "household_rates_from" edges to HouseholdRate entities.
func (_u *HouseholdCurrencyUpdate) RemoveHouseholdRatesFrom(v ...*HouseholdRate) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHouseholdRatesFromIDs(ids...)
}

// ClearHouseholdRatesTo clears all "household_rates_to" edges to the HouseholdRate entity.
func (_u *HouseholdCurrencyUpdate) ClearHouseholdRatesTo() *HouseholdCurrencyUpdate {
	_u.mutation.ClearHouseholdRatesTo()
	return _u
}

// RemoveHouseholdRatesToIDs removes the "household_rates_to" edge to HouseholdRate entities by IDs.
func (_u *HouseholdCurrencyUpdate) RemoveHouseholdRatesToIDs(ids ...int) *HouseholdCurrencyUpdate {
	_u.mutation.RemoveHouseholdRatesToIDs(ids...)
	return _u
}

// RemoveHouseholdRatesTo removes "household_rates_to" edges to HouseholdRate entities.
func (_u *HouseholdCurrencyUpdate) RemoveHouseholdRatesTo(v ...*HouseholdRate) *HouseholdCurrencyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHouseholdRatesToIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HouseholdCurrencyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HouseholdCurrencyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HouseholdCurrencyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HouseholdCurrencyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HouseholdCurrencyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if householdcurrency.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized householdcurrency.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := householdcurrency.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *HouseholdCurrencyUpdate) check() error {
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HouseholdCurrency.household"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HouseholdCurrencyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HouseholdCurrencyUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HouseholdCurrencyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(householdcurrency.Table, householdcurrency.Columns, sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(householdcurrency.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Important(); ok {
		_spec.SetField(householdcurrency.FieldImportant, field.TypeBool, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.AccountsTable,
			Columns: []string{householdcurrency.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.AccountsTable,
			Columns: []string{householdcurrency.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.AccountsTable,
			Columns: []string{householdcurrency.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvestmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.InvestmentsTable,
			Columns: []string{householdcurrency.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvestmentsIDs(); len(nodes) > 0 && !_u.mutation.InvestmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.InvestmentsTable,
			Columns: []string{householdcurrency.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvestmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.InvestmentsTable,
			Columns: []string{householdcurrency.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.TransactionEntriesTable,
			Columns: []string{householdcurrency.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionEntriesIDs(); len(nodes) > 0 && !_u.mutation.TransactionEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.TransactionEntriesTable,
			Columns: []string{householdcurrency.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.TransactionEntriesTable,
			Columns: []string{householdcurrency.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecurringSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.RecurringSubscriptionsTable,
			Columns: []string{householdcurrency.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecurringSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.RecurringSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.RecurringSubscriptionsTable,
			Columns: []string{householdcurrency.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.RecurringSubscriptionsTable,
			Columns: []string{householdcurrency.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotEntriesTable,
			Columns: []string{householdcurrency.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotEntriesIDs(); len(nodes) > 0 && !_u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotEntriesTable,
			Columns: []string{householdcurrency.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotEntriesTable,
			Columns: []string{householdcurrency.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotRatesFromCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesFromTable,
			Columns: []string{householdcurrency.SnapshotRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotRatesFromIDs(); len(nodes) > 0 && !_u.mutation.SnapshotRatesFromCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesFromTable,
			Columns: []string{householdcurrency.SnapshotRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotRatesFromIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesFromTable,
			Columns: []string{householdcurrency.SnapshotRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotRatesToCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesToTable,
			Columns: []string{householdcurrency.SnapshotRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotRatesToIDs(); len(nodes) > 0 && !_u.mutation.SnapshotRatesToCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesToTable,
			Columns: []string{householdcurrency.SnapshotRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotRatesToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesToTable,
			Columns: []string{householdcurrency.SnapshotRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HouseholdRatesFromCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesFromTable,
			Columns: []string{householdcurrency.HouseholdRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHouseholdRatesFromIDs(); len(nodes) > 0 && !_u.mutation.HouseholdRatesFromCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesFromTable,
			Columns: []string{householdcurrency.HouseholdRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdRatesFromIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesFromTable,
			Columns: []string{householdcurrency.HouseholdRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HouseholdRatesToCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesToTable,
			Columns: []string{householdcurrency.HouseholdRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHouseholdRatesToIDs(); len(nodes) > 0 && !_u.mutation.HouseholdRatesToCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesToTable,
			Columns: []string{householdcurrency.HouseholdRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdRatesToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesToTable,
			Columns: []string{householdcurrency.HouseholdRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{householdcurrency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HouseholdCurrencyUpdateOne is the builder for updating a single HouseholdCurrency entity.
type HouseholdCurrencyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *HouseholdCurrencyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *HouseholdCurrencyUpdateOne) SetUpdateTime(v time.Time) *HouseholdCurrencyUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetImportant sets the "important" field.
func (_u *HouseholdCurrencyUpdateOne) SetImportant(v bool) *HouseholdCurrencyUpdateOne {
	_u.mutation.SetImportant(v)
	return _u
}

// SetNillableImportant sets the "important" field if the given value is not nil.
func (_u *HouseholdCurrencyUpdateOne) SetNillableImportant(v *bool) *HouseholdCurrencyUpdateOne {
	if v != nil {
		_u.SetImportant(*v)
	}
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *HouseholdCurrencyUpdateOne) AddAccountIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *HouseholdCurrencyUpdateOne) AddAccounts(v ...*Account) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddInvestmentIDs adds the "investments" edge to the Investment entity by IDs.
func (_u *HouseholdCurrencyUpdateOne) AddInvestmentIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.AddInvestmentIDs(ids...)
	return _u
}

// AddInvestments adds the "investments" edges to the Investment entity.
func (_u *HouseholdCurrencyUpdateOne) AddInvestments(v ...*Investment) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvestmentIDs(ids...)
}

// AddTransactionEntryIDs adds the "transaction_entries" edge to the TransactionEntry entity by IDs.
func (_u *HouseholdCurrencyUpdateOne) AddTransactionEntryIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.AddTransactionEntryIDs(ids...)
	return _u
}

// AddTransactionEntries adds the "transaction_entries" edges to the TransactionEntry entity.
func (_u *HouseholdCurrencyUpdateOne) AddTransactionEntries(v ...*TransactionEntry) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionEntryIDs(ids...)
}

// AddRecurringSubscriptionIDs adds the "recurring_subscriptions" edge to the RecurringSubscription entity by IDs.
func (_u *HouseholdCurrencyUpdateOne) AddRecurringSubscriptionIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.AddRecurringSubscriptionIDs(ids...)
	return _u
}

// AddRecurringSubscriptions adds the "recurring_subscriptions" edges to the RecurringSubscription entity.
func (_u *HouseholdCurrencyUpdateOne) AddRecurringSubscriptions(v ...*RecurringSubscription) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecurringSubscriptionIDs(ids...)
}

// AddSnapshotEntryIDs adds the "snapshot_entries" edge to the SnapshotEntry entity by IDs.
func (_u *HouseholdCurrencyUpdateOne) AddSnapshotEntryIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.AddSnapshotEntryIDs(ids...)
	return _u
}

// AddSnapshotEntries adds the "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *HouseholdCurrencyUpdateOne) AddSnapshotEntries(v ...*SnapshotEntry) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotEntryIDs(ids...)
}

// AddSnapshotRatesFromIDs adds the "snapshot_rates_from" edge to the SnapshotRate entity by IDs.
func (_u *HouseholdCurrencyUpdateOne) AddSnapshotRatesFromIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.AddSnapshotRatesFromIDs(ids...)
	return _u
}

// AddSnapshotRatesFrom adds the "snapshot_rates_from" edges to the SnapshotRate entity.
func (_u *HouseholdCurrencyUpdateOne) AddSnapshotRatesFrom(v ...*SnapshotRate) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotRatesFromIDs(ids...)
}

// AddSnapshotRatesToIDs adds the "snapshot_rates_to" edge to the SnapshotRate entity by IDs.
func (_u *HouseholdCurrencyUpdateOne) AddSnapshotRatesToIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.AddSnapshotRatesToIDs(ids...)
	return _u
}

// AddSnapshotRatesTo adds the "snapshot_rates_to" edges to the SnapshotRate entity.
func (_u *HouseholdCurrencyUpdateOne) AddSnapshotRatesTo(v ...*SnapshotRate) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotRatesToIDs(ids...)
}

// AddHouseholdRatesFromIDs adds the "household_rates_from" edge to the HouseholdRate entity by IDs.
func (_u *HouseholdCurrencyUpdateOne) AddHouseholdRatesFromIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.AddHouseholdRatesFromIDs(ids...)
	return _u
}

// AddHouseholdRatesFrom adds the "household_rates_from" edges to the HouseholdRate entity.
func (_u *HouseholdCurrencyUpdateOne) AddHouseholdRatesFrom(v ...*HouseholdRate) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHouseholdRatesFromIDs(ids...)
}

// AddHouseholdRatesToIDs adds the "household_rates_to" edge to the HouseholdRate entity by IDs.
func (_u *HouseholdCurrencyUpdateOne) AddHouseholdRatesToIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.AddHouseholdRatesToIDs(ids...)
	return _u
}

// AddHouseholdRatesTo adds the "household_rates_to" edges to the HouseholdRate entity.
func (_u *HouseholdCurrencyUpdateOne) AddHouseholdRatesTo(v ...*HouseholdRate) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHouseholdRatesToIDs(ids...)
}

// Mutation returns the HouseholdCurrencyMutation object of the builder.
func (_u *HouseholdCurrencyUpdateOne) Mutation() *HouseholdCurrencyMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *HouseholdCurrencyUpdateOne) ClearAccounts() *HouseholdCurrencyUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *HouseholdCurrencyUpdateOne) RemoveAccountIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *HouseholdCurrencyUpdateOne) RemoveAccounts(v ...*Account) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearInvestments clears all "investments" edges to the Investment entity.
func (_u *HouseholdCurrencyUpdateOne) ClearInvestments() *HouseholdCurrencyUpdateOne {
	_u.mutation.ClearInvestments()
	return _u
}

// RemoveInvestmentIDs removes the "investments" edge to Investment entities by IDs.
func (_u *HouseholdCurrencyUpdateOne) RemoveInvestmentIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.RemoveInvestmentIDs(ids...)
	return _u
}

// RemoveInvestments removes "investments" edges to Investment entities.
func (_u *HouseholdCurrencyUpdateOne) RemoveInvestments(v ...*Investment) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvestmentIDs(ids...)
}

// ClearTransactionEntries clears all "transaction_entries" edges to the TransactionEntry entity.
func (_u *HouseholdCurrencyUpdateOne) ClearTransactionEntries() *HouseholdCurrencyUpdateOne {
	_u.mutation.ClearTransactionEntries()
	return _u
}

// RemoveTransactionEntryIDs removes the "transaction_entries" edge to TransactionEntry entities by IDs.
func (_u *HouseholdCurrencyUpdateOne) RemoveTransactionEntryIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.RemoveTransactionEntryIDs(ids...)
	return _u
}

// RemoveTransactionEntries removes "transaction_entries" edges to TransactionEntry entities.
func (_u *HouseholdCurrencyUpdateOne) RemoveTransactionEntries(v ...*TransactionEntry) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionEntryIDs(ids...)
}

// ClearRecurringSubscriptions clears all "recurring_subscriptions" edges to the RecurringSubscription entity.
func (_u *HouseholdCurrencyUpdateOne) ClearRecurringSubscriptions() *HouseholdCurrencyUpdateOne {
	_u.mutation.ClearRecurringSubscriptions()
	return _u
}

// RemoveRecurringSubscriptionIDs removes the "recurring_subscriptions" edge to RecurringSubscription entities by IDs.
func (_u *HouseholdCurrencyUpdateOne) RemoveRecurringSubscriptionIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.RemoveRecurringSubscriptionIDs(ids...)
	return _u
}

// RemoveRecurringSubscriptions removes "recurring_subscriptions" edges to RecurringSubscription entities.
func (_u *HouseholdCurrencyUpdateOne) RemoveRecurringSubscriptions(v ...*RecurringSubscription) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecurringSubscriptionIDs(ids...)
}

// ClearSnapshotEntries clears all "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *HouseholdCurrencyUpdateOne) ClearSnapshotEntries() *HouseholdCurrencyUpdateOne {
	_u.mutation.ClearSnapshotEntries()
	return _u
}

// RemoveSnapshotEntryIDs removes the "snapshot_entries" edge to SnapshotEntry entities by IDs.
func (_u *HouseholdCurrencyUpdateOne) RemoveSnapshotEntryIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.RemoveSnapshotEntryIDs(ids...)
	return _u
}

// RemoveSnapshotEntries removes "snapshot_entries" edges to SnapshotEntry entities.
func (_u *HouseholdCurrencyUpdateOne) RemoveSnapshotEntries(v ...*SnapshotEntry) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotEntryIDs(ids...)
}

// ClearSnapshotRatesFrom clears all "snapshot_rates_from" edges to the SnapshotRate entity.
func (_u *HouseholdCurrencyUpdateOne) ClearSnapshotRatesFrom() *HouseholdCurrencyUpdateOne {
	_u.mutation.ClearSnapshotRatesFrom()
	return _u
}

// RemoveSnapshotRatesFromIDs removes the "snapshot_rates_from" edge to SnapshotRate entities by IDs.
func (_u *HouseholdCurrencyUpdateOne) RemoveSnapshotRatesFromIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.RemoveSnapshotRatesFromIDs(ids...)
	return _u
}

// RemoveSnapshotRatesFrom removes "snapshot_rates_from" edges to SnapshotRate entities.
func (_u *HouseholdCurrencyUpdateOne) RemoveSnapshotRatesFrom(v ...*SnapshotRate) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotRatesFromIDs(ids...)
}

// ClearSnapshotRatesTo clears all "snapshot_rates_to" edges to the SnapshotRate entity.
func (_u *HouseholdCurrencyUpdateOne) ClearSnapshotRatesTo() *HouseholdCurrencyUpdateOne {
	_u.mutation.ClearSnapshotRatesTo()
	return _u
}

// RemoveSnapshotRatesToIDs removes the "snapshot_rates_to" edge to SnapshotRate entities by IDs.
func (_u *HouseholdCurrencyUpdateOne) RemoveSnapshotRatesToIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.RemoveSnapshotRatesToIDs(ids...)
	return _u
}

// RemoveSnapshotRatesTo removes "snapshot_rates_to" edges to SnapshotRate entities.
func (_u *HouseholdCurrencyUpdateOne) RemoveSnapshotRatesTo(v ...*SnapshotRate) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotRatesToIDs(ids...)
}

// ClearHouseholdRatesFrom clears all "household_rates_from" edges to the HouseholdRate entity.
func (_u *HouseholdCurrencyUpdateOne) ClearHouseholdRatesFrom() *HouseholdCurrencyUpdateOne {
	_u.mutation.ClearHouseholdRatesFrom()
	return _u
}

// RemoveHouseholdRatesFromIDs removes the "household_rates_from" edge to HouseholdRate entities by IDs.
func (_u *HouseholdCurrencyUpdateOne) RemoveHouseholdRatesFromIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.RemoveHouseholdRatesFromIDs(ids...)
	return _u
}

// RemoveHouseholdRatesFrom removes "household_rates_from" edges to HouseholdRate entities.
func (_u *HouseholdCurrencyUpdateOne) RemoveHouseholdRatesFrom(v ...*HouseholdRate) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHouseholdRatesFromIDs(ids...)
}

// ClearHouseholdRatesTo clears all "household_rates_to" edges to the HouseholdRate entity.
func (_u *HouseholdCurrencyUpdateOne) ClearHouseholdRatesTo() *HouseholdCurrencyUpdateOne {
	_u.mutation.ClearHouseholdRatesTo()
	return _u
}

// RemoveHouseholdRatesToIDs removes the "household_rates_to" edge to HouseholdRate entities by IDs.
func (_u *HouseholdCurrencyUpdateOne) RemoveHouseholdRatesToIDs(ids ...int) *HouseholdCurrencyUpdateOne {
	_u.mutation.RemoveHouseholdRatesToIDs(ids...)
	return _u
}

// RemoveHouseholdRatesTo removes "household_rates_to" edges to HouseholdRate entities.
func (_u *HouseholdCurrencyUpdateOne) RemoveHouseholdRatesTo(v ...*HouseholdRate) *HouseholdCurrencyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHouseholdRatesToIDs(ids...)
}

// Where appends a list predicates to the HouseholdCurrencyUpdate builder.
func (_u *HouseholdCurrencyUpdateOne) Where(ps ...predicate.HouseholdCurrency) *HouseholdCurrencyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HouseholdCurrencyUpdateOne) Select(field string, fields ...string) *HouseholdCurrencyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HouseholdCurrency entity.
func (_u *HouseholdCurrencyUpdateOne) Save(ctx context.Context) (*HouseholdCurrency, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HouseholdCurrencyUpdateOne) SaveX(ctx context.Context) *HouseholdCurrency {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HouseholdCurrencyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HouseholdCurrencyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HouseholdCurrencyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if householdcurrency.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized householdcurrency.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := householdcurrency.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *HouseholdCurrencyUpdateOne) check() error {
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HouseholdCurrency.household"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HouseholdCurrencyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HouseholdCurrencyUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HouseholdCurrencyUpdateOne) sqlSave(ctx context.Context) (_node *HouseholdCurrency, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(householdcurrency.Table, householdcurrency.Columns, sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HouseholdCurrency.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, householdcurrency.FieldID)
		for _, f := range fields {
			if !householdcurrency.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != householdcurrency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(householdcurrency.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Important(); ok {
		_spec.SetField(householdcurrency.FieldImportant, field.TypeBool, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.AccountsTable,
			Columns: []string{householdcurrency.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.AccountsTable,
			Columns: []string{householdcurrency.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.AccountsTable,
			Columns: []string{householdcurrency.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvestmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.InvestmentsTable,
			Columns: []string{householdcurrency.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvestmentsIDs(); len(nodes) > 0 && !_u.mutation.InvestmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.InvestmentsTable,
			Columns: []string{householdcurrency.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvestmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.InvestmentsTable,
			Columns: []string{householdcurrency.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.TransactionEntriesTable,
			Columns: []string{householdcurrency.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionEntriesIDs(); len(nodes) > 0 && !_u.mutation.TransactionEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.TransactionEntriesTable,
			Columns: []string{householdcurrency.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.TransactionEntriesTable,
			Columns: []string{householdcurrency.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecurringSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.RecurringSubscriptionsTable,
			Columns: []string{householdcurrency.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecurringSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.RecurringSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.RecurringSubscriptionsTable,
			Columns: []string{householdcurrency.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.RecurringSubscriptionsTable,
			Columns: []string{householdcurrency.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotEntriesTable,
			Columns: []string{householdcurrency.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotEntriesIDs(); len(nodes) > 0 && !_u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotEntriesTable,
			Columns: []string{householdcurrency.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotEntriesTable,
			Columns: []string{householdcurrency.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotRatesFromCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesFromTable,
			Columns: []string{householdcurrency.SnapshotRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotRatesFromIDs(); len(nodes) > 0 && !_u.mutation.SnapshotRatesFromCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesFromTable,
			Columns: []string{householdcurrency.SnapshotRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotRatesFromIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesFromTable,
			Columns: []string{householdcurrency.SnapshotRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotRatesToCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesToTable,
			Columns: []string{householdcurrency.SnapshotRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotRatesToIDs(); len(nodes) > 0 && !_u.mutation.SnapshotRatesToCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesToTable,
			Columns: []string{householdcurrency.SnapshotRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotRatesToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.SnapshotRatesToTable,
			Columns: []string{householdcurrency.SnapshotRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HouseholdRatesFromCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesFromTable,
			Columns: []string{householdcurrency.HouseholdRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHouseholdRatesFromIDs(); len(nodes) > 0 && !_u.mutation.HouseholdRatesFromCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesFromTable,
			Columns: []string{householdcurrency.HouseholdRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdRatesFromIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesFromTable,
			Columns: []string{householdcurrency.HouseholdRatesFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HouseholdRatesToCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesToTable,
			Columns: []string{householdcurrency.HouseholdRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHouseholdRatesToIDs(); len(nodes) > 0 && !_u.mutation.HouseholdRatesToCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesToTable,
			Columns: []string{householdcurrency.HouseholdRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdRatesToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   householdcurrency.HouseholdRatesToTable,
			Columns: []string{householdcurrency.HouseholdRatesToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &HouseholdCurrency{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{householdcurrency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
