// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"beavermoney.app/ent/currency"
	"beavermoney.app/ent/household"
	"beavermoney.app/ent/householdrate"
	"beavermoney.app/ent/predicate"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HouseholdRateQuery is the builder for querying HouseholdRate entities.
type HouseholdRateQuery struct {
	config
	ctx              *QueryContext
	order            []householdrate.OrderOption
	inters           []Interceptor
	predicates       []predicate.HouseholdRate
	withHousehold    *HouseholdQuery
	withFromCurrency *CurrencyQuery
	withToCurrency   *CurrencyQuery
	loadTotal        []func(context.Context, []*HouseholdRate) error
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HouseholdRateQuery builder.
func (_q *HouseholdRateQuery) Where(ps ...predicate.HouseholdRate) *HouseholdRateQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *HouseholdRateQuery) Limit(limit int) *HouseholdRateQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *HouseholdRateQuery) Offset(offset int) *HouseholdRateQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *HouseholdRateQuery) Unique(unique bool) *HouseholdRateQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *HouseholdRateQuery) Order(o ...householdrate.OrderOption) *HouseholdRateQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryHousehold chains the current query on the "household" edge.
func (_q *HouseholdRateQuery) QueryHousehold() *HouseholdQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(householdrate.Table, householdrate.FieldID, selector),
			sqlgraph.To(household.Table, household.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, householdrate.HouseholdTable, householdrate.HouseholdColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFromCurrency chains the current query on the "from_currency" edge.
func (_q *HouseholdRateQuery) QueryFromCurrency() *CurrencyQuery {
	query := (&CurrencyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(householdrate.Table, householdrate.FieldID, selector),
			sqlgraph.To(currency.Table, currency.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, householdrate.FromCurrencyTable, householdrate.FromCurrencyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryToCurrency chains the current query on the "to_currency" edge.
func (_q *HouseholdRateQuery) QueryToCurrency() *CurrencyQuery {
	query := (&CurrencyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(householdrate.Table, householdrate.FieldID, selector),
			sqlgraph.To(currency.Table, currency.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, householdrate.ToCurrencyTable, householdrate.ToCurrencyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HouseholdRate entity from the query.
// Returns a *NotFoundError when no HouseholdRate was found.
func (_q *HouseholdRateQuery) First(ctx context.Context) (*HouseholdRate, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{householdrate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *HouseholdRateQuery) FirstX(ctx context.Context) *HouseholdRate {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HouseholdRate ID from the query.
// Returns a *NotFoundError when no HouseholdRate ID was found.
func (_q *HouseholdRateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{householdrate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *HouseholdRateQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HouseholdRate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HouseholdRate entity is found.
// Returns a *NotFoundError when no HouseholdRate entities are found.
func (_q *HouseholdRateQuery) Only(ctx context.Context) (*HouseholdRate, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{householdrate.Label}
	default:
		return nil, &NotSingularError{householdrate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *HouseholdRateQuery) OnlyX(ctx context.Context) *HouseholdRate {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HouseholdRate ID in the query.
// Returns a *NotSingularError when more than one HouseholdRate ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *HouseholdRateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{householdrate.Label}
	default:
		err = &NotSingularError{householdrate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *HouseholdRateQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HouseholdRates.
func (_q *HouseholdRateQuery) All(ctx context.Context) ([]*HouseholdRate, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HouseholdRate, *HouseholdRateQuery]()
	return withInterceptors[[]*HouseholdRate](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *HouseholdRateQuery) AllX(ctx context.Context) []*HouseholdRate {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HouseholdRate IDs.
func (_q *HouseholdRateQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(householdrate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *HouseholdRateQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *HouseholdRateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*HouseholdRateQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *HouseholdRateQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *HouseholdRateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *HouseholdRateQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HouseholdRateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *HouseholdRateQuery) Clone() *HouseholdRateQuery {
	if _q == nil {
		return nil
	}
	return &HouseholdRateQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]householdrate.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.HouseholdRate{}, _q.predicates...),
		withHousehold:    _q.withHousehold.Clone(),
		withFromCurrency: _q.withFromCurrency.Clone(),
		withToCurrency:   _q.withToCurrency.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithHousehold tells the query-builder to eager-load the nodes that are connected to
// the "household" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HouseholdRateQuery) WithHousehold(opts ...func(*HouseholdQuery)) *HouseholdRateQuery {
	query := (&HouseholdClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHousehold = query
	return _q
}

// WithFromCurrency tells the query-builder to eager-load the nodes that are connected to
// the "from_currency" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HouseholdRateQuery) WithFromCurrency(opts ...func(*CurrencyQuery)) *HouseholdRateQuery {
	query := (&CurrencyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFromCurrency = query
	return _q
}

// WithToCurrency tells the query-builder to eager-load the nodes that are connected to
// the "to_currency" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HouseholdRateQuery) WithToCurrency(opts ...func(*CurrencyQuery)) *HouseholdRateQuery {
	query := (&CurrencyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withToCurrency = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		HouseholdID int `json:"household_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HouseholdRate.Query().
//		GroupBy(householdrate.FieldHouseholdID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *HouseholdRateQuery) GroupBy(field string, fields ...string) *HouseholdRateGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HouseholdRateGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = householdrate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		HouseholdID int `json:"household_id,omitempty"`
//	}
//
//	client.HouseholdRate.Query().
//		Select(householdrate.FieldHouseholdID).
//		Scan(ctx, &v)
func (_q *HouseholdRateQuery) Select(fields ...string) *HouseholdRateSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &HouseholdRateSelect{HouseholdRateQuery: _q}
	sbuild.label = householdrate.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HouseholdRateSelect configured with the given aggregations.
func (_q *HouseholdRateQuery) Aggregate(fns ...AggregateFunc) *HouseholdRateSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *HouseholdRateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !householdrate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if householdrate.Policy == nil {
		return errors.New("ent: uninitialized householdrate.Policy (forgotten import ent/runtime?)")
	}
	if err := householdrate.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *HouseholdRateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HouseholdRate, error) {
	var (
		nodes       = []*HouseholdRate{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withHousehold != nil,
			_q.withFromCurrency != nil,
			_q.withToCurrency != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HouseholdRate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HouseholdRate{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withHousehold; query != nil {
		if err := _q.loadHousehold(ctx, query, nodes, nil,
			func(n *HouseholdRate, e *Household) { n.Edges.Household = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFromCurrency; query != nil {
		if err := _q.loadFromCurrency(ctx, query, nodes, nil,
			func(n *HouseholdRate, e *Currency) { n.Edges.FromCurrency = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withToCurrency; query != nil {
		if err := _q.loadToCurrency(ctx, query, nodes, nil,
			func(n *HouseholdRate, e *Currency) { n.Edges.ToCurrency = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *HouseholdRateQuery) loadHousehold(ctx context.Context, query *HouseholdQuery, nodes []*HouseholdRate, init func(*HouseholdRate), assign func(*HouseholdRate, *Household)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HouseholdRate)
	for i := range nodes {
		fk := nodes[i].HouseholdID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(household.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "household_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *HouseholdRateQuery) loadFromCurrency(ctx context.Context, query *CurrencyQuery, nodes []*HouseholdRate, init func(*HouseholdRate), assign func(*HouseholdRate, *Currency)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HouseholdRate)
	for i := range nodes {
		fk := nodes[i].FromCurrencyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(currency.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "from_currency_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *HouseholdRateQuery) loadToCurrency(ctx context.Context, query *CurrencyQuery, nodes []*HouseholdRate, init func(*HouseholdRate), assign func(*HouseholdRate, *Currency)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HouseholdRate)
	for i := range nodes {
		fk := nodes[i].ToCurrencyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(currency.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "to_currency_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *HouseholdRateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *HouseholdRateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(householdrate.Table, householdrate.Columns, sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, householdrate.FieldID)
		for i := range fields {
			if fields[i] != householdrate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withHousehold != nil {
			_spec.Node.AddColumnOnce(householdrate.FieldHouseholdID)
		}
		if _q.withFromCurrency != nil {
			_spec.Node.AddColumnOnce(householdrate.FieldFromCurrencyID)
		}
		if _q.withToCurrency != nil {
			_spec.Node.AddColumnOnce(householdrate.FieldToCurrencyID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *HouseholdRateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(householdrate.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = householdrate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *HouseholdRateQuery) Modify(modifiers ...func(s *sql.Selector)) *HouseholdRateSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// HouseholdRateGroupBy is the group-by builder for HouseholdRate entities.
type HouseholdRateGroupBy struct {
	selector
	build *HouseholdRateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *HouseholdRateGroupBy) Aggregate(fns ...AggregateFunc) *HouseholdRateGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *HouseholdRateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HouseholdRateQuery, *HouseholdRateGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *HouseholdRateGroupBy) sqlScan(ctx context.Context, root *HouseholdRateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HouseholdRateSelect is the builder for selecting fields of HouseholdRate entities.
type HouseholdRateSelect struct {
	*HouseholdRateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *HouseholdRateSelect) Aggregate(fns ...AggregateFunc) *HouseholdRateSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *HouseholdRateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HouseholdRateQuery, *HouseholdRateSelect](ctx, _s.HouseholdRateQuery, _s, _s.inters, v)
}

func (_s *HouseholdRateSelect) sqlScan(ctx context.Context, root *HouseholdRateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *HouseholdRateSelect) Modify(modifiers ...func(s *sql.Selector)) *HouseholdRateSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
