// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"beavermoney.app/ent/account"
	"beavermoney.app/ent/household"
	"beavermoney.app/ent/householdcurrency"
	"beavermoney.app/ent/householdrate"
	"beavermoney.app/ent/investment"
	"beavermoney.app/ent/investmentlot"
	"beavermoney.app/ent/predicate"
	"beavermoney.app/ent/recurringsubscription"
	"beavermoney.app/ent/snapshot"
	"beavermoney.app/ent/snapshotentry"
	"beavermoney.app/ent/transaction"
	"beavermoney.app/ent/transactioncategory"
	"beavermoney.app/ent/transactionentry"
	"beavermoney.app/ent/user"
	"beavermoney.app/ent/userhousehold"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HouseholdUpdate is the builder for updating Household entities.
type HouseholdUpdate struct {
	config
	hooks     []Hook
	mutation  *HouseholdMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the HouseholdUpdate builder.
func (_u *HouseholdUpdate) Where(ps ...predicate.Household) *HouseholdUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *HouseholdUpdate) SetUpdateTime(v time.Time) *HouseholdUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *HouseholdUpdate) SetName(v string) *HouseholdUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HouseholdUpdate) SetNillableName(v *string) *HouseholdUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLocale sets the "locale" field.
func (_u *HouseholdUpdate) SetLocale(v string) *HouseholdUpdate {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *HouseholdUpdate) SetNillableLocale(v *string) *HouseholdUpdate {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// SetCurrencyCode sets the "currency_code" field.
func (_u *HouseholdUpdate) SetCurrencyCode(v string) *HouseholdUpdate {
	_u.mutation.SetCurrencyCode(v)
	return _u
}

// SetNillableCurrencyCode sets the "currency_code" field if the given value is not nil.
func (_u *HouseholdUpdate) SetNillableCurrencyCode(v *string) *HouseholdUpdate {
	if v != nil {
		_u.SetCurrencyCode(*v)
	}
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *HouseholdUpdate) AddUserIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *HouseholdUpdate) AddUsers(v ...*User) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *HouseholdUpdate) AddAccountIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *HouseholdUpdate) AddAccounts(v ...*Account) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *HouseholdUpdate) AddTransactionIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *HouseholdUpdate) AddTransactions(v ...*Transaction) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddInvestmentIDs adds the "investments" edge to the Investment entity by IDs.
func (_u *HouseholdUpdate) AddInvestmentIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddInvestmentIDs(ids...)
	return _u
}

// AddInvestments adds the "investments" edges to the Investment entity.
func (_u *HouseholdUpdate) AddInvestments(v ...*Investment) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvestmentIDs(ids...)
}

// AddInvestmentLotIDs adds the "investment_lots" edge to the InvestmentLot entity by IDs.
func (_u *HouseholdUpdate) AddInvestmentLotIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddInvestmentLotIDs(ids...)
	return _u
}

// AddInvestmentLots adds the "investment_lots" edges to the InvestmentLot entity.
func (_u *HouseholdUpdate) AddInvestmentLots(v ...*InvestmentLot) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvestmentLotIDs(ids...)
}

// AddTransactionCategoryIDs adds the "transaction_categories" edge to the TransactionCategory entity by IDs.
func (_u *HouseholdUpdate) AddTransactionCategoryIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddTransactionCategoryIDs(ids...)
	return _u
}

// AddTransactionCategories adds the "transaction_categories" edges to the TransactionCategory entity.
func (_u *HouseholdUpdate) AddTransactionCategories(v ...*TransactionCategory) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionCategoryIDs(ids...)
}

// AddTransactionEntryIDs adds the "transaction_entries" edge to the TransactionEntry entity by IDs.
func (_u *HouseholdUpdate) AddTransactionEntryIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddTransactionEntryIDs(ids...)
	return _u
}

// AddTransactionEntries adds the "transaction_entries" edges to the TransactionEntry entity.
func (_u *HouseholdUpdate) AddTransactionEntries(v ...*TransactionEntry) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionEntryIDs(ids...)
}

// AddRecurringSubscriptionIDs adds the "recurring_subscriptions" edge to the RecurringSubscription entity by IDs.
func (_u *HouseholdUpdate) AddRecurringSubscriptionIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddRecurringSubscriptionIDs(ids...)
	return _u
}

// AddRecurringSubscriptions adds the "recurring_subscriptions" edges to the RecurringSubscription entity.
func (_u *HouseholdUpdate) AddRecurringSubscriptions(v ...*RecurringSubscription) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecurringSubscriptionIDs(ids...)
}

// AddSnapshotIDs adds the "snapshots" edge to the Snapshot entity by IDs.
func (_u *HouseholdUpdate) AddSnapshotIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the Snapshot entity.
func (_u *HouseholdUpdate) AddSnapshots(v ...*Snapshot) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddSnapshotEntryIDs adds the "snapshot_entries" edge to the SnapshotEntry entity by IDs.
func (_u *HouseholdUpdate) AddSnapshotEntryIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddSnapshotEntryIDs(ids...)
	return _u
}

// AddSnapshotEntries adds the "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *HouseholdUpdate) AddSnapshotEntries(v ...*SnapshotEntry) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotEntryIDs(ids...)
}

// AddHouseholdCurrencyIDs adds the "household_currencies" edge to the HouseholdCurrency entity by IDs.
func (_u *HouseholdUpdate) AddHouseholdCurrencyIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddHouseholdCurrencyIDs(ids...)
	return _u
}

// AddHouseholdCurrencies adds the "household_currencies" edges to the HouseholdCurrency entity.
func (_u *HouseholdUpdate) AddHouseholdCurrencies(v ...*HouseholdCurrency) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHouseholdCurrencyIDs(ids...)
}

// AddHouseholdRateIDs adds the "household_rates" edge to the HouseholdRate entity by IDs.
func (_u *HouseholdUpdate) AddHouseholdRateIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddHouseholdRateIDs(ids...)
	return _u
}

// AddHouseholdRates adds the "household_rates" edges to the HouseholdRate entity.
func (_u *HouseholdUpdate) AddHouseholdRates(v ...*HouseholdRate) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHouseholdRateIDs(ids...)
}

// AddUserHouseholdIDs adds the "user_households" edge to the UserHousehold entity by IDs.
func (_u *HouseholdUpdate) AddUserHouseholdIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.AddUserHouseholdIDs(ids...)
	return _u
}

// AddUserHouseholds adds the "user_households" edges to the UserHousehold entity.
func (_u *HouseholdUpdate) AddUserHouseholds(v ...*UserHousehold) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserHouseholdIDs(ids...)
}

// Mutation returns the HouseholdMutation object of the builder.
func (_u *HouseholdUpdate) Mutation() *HouseholdMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *HouseholdUpdate) ClearUsers() *HouseholdUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *HouseholdUpdate) RemoveUserIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *HouseholdUpdate) RemoveUsers(v ...*User) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *HouseholdUpdate) ClearAccounts() *HouseholdUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *HouseholdUpdate) RemoveAccountIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *HouseholdUpdate) RemoveAccounts(v ...*Account) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *HouseholdUpdate) ClearTransactions() *HouseholdUpdate {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *HouseholdUpdate) RemoveTransactionIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *HouseholdUpdate) RemoveTransactions(v ...*Transaction) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearInvestments clears all "investments" edges to the Investment entity.
func (_u *HouseholdUpdate) ClearInvestments() *HouseholdUpdate {
	_u.mutation.ClearInvestments()
	return _u
}

// RemoveInvestmentIDs removes the "investments" edge to Investment entities by IDs.
func (_u *HouseholdUpdate) RemoveInvestmentIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveInvestmentIDs(ids...)
	return _u
}

// RemoveInvestments removes "investments" edges to Investment entities.
func (_u *HouseholdUpdate) RemoveInvestments(v ...*Investment) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvestmentIDs(ids...)
}

// ClearInvestmentLots clears all "investment_lots" edges to the InvestmentLot entity.
func (_u *HouseholdUpdate) ClearInvestmentLots() *HouseholdUpdate {
	_u.mutation.ClearInvestmentLots()
	return _u
}

// RemoveInvestmentLotIDs removes the "investment_lots" edge to InvestmentLot entities by IDs.
func (_u *HouseholdUpdate) RemoveInvestmentLotIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveInvestmentLotIDs(ids...)
	return _u
}

// RemoveInvestmentLots removes "investment_lots" edges to InvestmentLot entities.
func (_u *HouseholdUpdate) RemoveInvestmentLots(v ...*InvestmentLot) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvestmentLotIDs(ids...)
}

// ClearTransactionCategories clears all "transaction_categories" edges to the TransactionCategory entity.
func (_u *HouseholdUpdate) ClearTransactionCategories() *HouseholdUpdate {
	_u.mutation.ClearTransactionCategories()
	return _u
}

// RemoveTransactionCategoryIDs removes the "transaction_categories" edge to TransactionCategory entities by IDs.
func (_u *HouseholdUpdate) RemoveTransactionCategoryIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveTransactionCategoryIDs(ids...)
	return _u
}

// RemoveTransactionCategories removes "transaction_categories" edges to TransactionCategory entities.
func (_u *HouseholdUpdate) RemoveTransactionCategories(v ...*TransactionCategory) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionCategoryIDs(ids...)
}

// ClearTransactionEntries clears all "transaction_entries" edges to the TransactionEntry entity.
func (_u *HouseholdUpdate) ClearTransactionEntries() *HouseholdUpdate {
	_u.mutation.ClearTransactionEntries()
	return _u
}

// RemoveTransactionEntryIDs removes the "transaction_entries" edge to TransactionEntry entities by IDs.
func (_u *HouseholdUpdate) RemoveTransactionEntryIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveTransactionEntryIDs(ids...)
	return _u
}

// RemoveTransactionEntries removes "transaction_entries" edges to TransactionEntry entities.
func (_u *HouseholdUpdate) RemoveTransactionEntries(v ...*TransactionEntry) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionEntryIDs(ids...)
}

// ClearRecurringSubscriptions clears all "recurring_subscriptions" edges to the RecurringSubscription entity.
func (_u *HouseholdUpdate) ClearRecurringSubscriptions() *HouseholdUpdate {
	_u.mutation.ClearRecurringSubscriptions()
	return _u
}

// RemoveRecurringSubscriptionIDs removes the "recurring_subscriptions" edge to RecurringSubscription entities by IDs.
func (_u *HouseholdUpdate) RemoveRecurringSubscriptionIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveRecurringSubscriptionIDs(ids...)
	return _u
}

// RemoveRecurringSubscriptions removes "recurring_subscriptions" edges to RecurringSubscription entities.
func (_u *HouseholdUpdate) RemoveRecurringSubscriptions(v ...*RecurringSubscription) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecurringSubscriptionIDs(ids...)
}

// ClearSnapshots clears all "snapshots" edges to the Snapshot entity.
func (_u *HouseholdUpdate) ClearSnapshots() *HouseholdUpdate {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to Snapshot entities by IDs.
func (_u *HouseholdUpdate) RemoveSnapshotIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to Snapshot entities.
func (_u *HouseholdUpdate) RemoveSnapshots(v ...*Snapshot) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearSnapshotEntries clears all "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *HouseholdUpdate) ClearSnapshotEntries() *HouseholdUpdate {
	_u.mutation.ClearSnapshotEntries()
	return _u
}

// RemoveSnapshotEntryIDs removes the "snapshot_entries" edge to SnapshotEntry entities by IDs.
func (_u *HouseholdUpdate) RemoveSnapshotEntryIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveSnapshotEntryIDs(ids...)
	return _u
}

// RemoveSnapshotEntries removes "snapshot_entries" edges to SnapshotEntry entities.
func (_u *HouseholdUpdate) RemoveSnapshotEntries(v ...*SnapshotEntry) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotEntryIDs(ids...)
}

// ClearHouseholdCurrencies clears all "household_currencies" edges to the HouseholdCurrency entity.
func (_u *HouseholdUpdate) ClearHouseholdCurrencies() *HouseholdUpdate {
	_u.mutation.ClearHouseholdCurrencies()
	return _u
}

// RemoveHouseholdCurrencyIDs removes the "household_currencies" edge to HouseholdCurrency entities by IDs.
func (_u *HouseholdUpdate) RemoveHouseholdCurrencyIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveHouseholdCurrencyIDs(ids...)
	return _u
}

// RemoveHouseholdCurrencies removes "household_currencies" edges to HouseholdCurrency entities.
func (_u *HouseholdUpdate) RemoveHouseholdCurrencies(v ...*HouseholdCurrency) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHouseholdCurrencyIDs(ids...)
}

// ClearHouseholdRates clears all "household_rates" edges to the HouseholdRate entity.
func (_u *HouseholdUpdate) ClearHouseholdRates() *HouseholdUpdate {
	_u.mutation.ClearHouseholdRates()
	return _u
}

// RemoveHouseholdRateIDs removes the "household_rates" edge to HouseholdRate entities by IDs.
func (_u *HouseholdUpdate) RemoveHouseholdRateIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveHouseholdRateIDs(ids...)
	return _u
}

// RemoveHouseholdRates removes "household_rates" edges to HouseholdRate entities.
func (_u *HouseholdUpdate) RemoveHouseholdRates(v ...*HouseholdRate) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHouseholdRateIDs(ids...)
}

// ClearUserHouseholds clears all "user_households" edges to the UserHousehold entity.
func (_u *HouseholdUpdate) ClearUserHouseholds() *HouseholdUpdate {
	_u.mutation.ClearUserHouseholds()
	return _u
}

// RemoveUserHouseholdIDs removes the "user_households" edge to UserHousehold entities by IDs.
func (_u *HouseholdUpdate) RemoveUserHouseholdIDs(ids ...int) *HouseholdUpdate {
	_u.mutation.RemoveUserHouseholdIDs(ids...)
	return _u
}

// RemoveUserHouseholds removes "user_households" edges to UserHousehold entities.
func (_u *HouseholdUpdate) RemoveUserHouseholds(v ...*UserHousehold) *HouseholdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserHouseholdIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HouseholdUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HouseholdUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HouseholdUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HouseholdUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HouseholdUpdate) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if household.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized household.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := household.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *HouseholdUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := household.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Household.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locale(); ok {
		if err := household.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "Household.locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrencyCode(); ok {
		if err := household.CurrencyCodeValidator(v); err != nil {
			return &ValidationError{Name: "currency_code", err: fmt.Errorf(`ent: validator failed for field "Household.currency_code": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HouseholdUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HouseholdUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HouseholdUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(household.Table, household.Columns, sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(household.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(household.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(household.FieldLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrencyCode(); ok {
		_spec.SetField(household.FieldCurrencyCode, field.TypeString, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   household.UsersTable,
			Columns: household.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		createE := &UserHouseholdCreate{config: _u.config, mutation: newUserHouseholdMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   household.UsersTable,
			Columns: household.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserHouseholdCreate{config: _u.config, mutation: newUserHouseholdMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   household.UsersTable,
			Columns: household.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserHouseholdCreate{config: _u.config, mutation: newUserHouseholdMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.AccountsTable,
			Columns: []string{household.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.AccountsTable,
			Columns: []string{household.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.AccountsTable,
			Columns: []string{household.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionsTable,
			Columns: []string{household.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionsTable,
			Columns: []string{household.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionsTable,
			Columns: []string{household.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvestmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentsTable,
			Columns: []string{household.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvestmentsIDs(); len(nodes) > 0 && !_u.mutation.InvestmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentsTable,
			Columns: []string{household.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvestmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentsTable,
			Columns: []string{household.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvestmentLotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentLotsTable,
			Columns: []string{household.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvestmentLotsIDs(); len(nodes) > 0 && !_u.mutation.InvestmentLotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentLotsTable,
			Columns: []string{household.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvestmentLotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentLotsTable,
			Columns: []string{household.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionCategoriesTable,
			Columns: []string{household.TransactionCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactioncategory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionCategoriesIDs(); len(nodes) > 0 && !_u.mutation.TransactionCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionCategoriesTable,
			Columns: []string{household.TransactionCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactioncategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionCategoriesTable,
			Columns: []string{household.TransactionCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactioncategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionEntriesTable,
			Columns: []string{household.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionEntriesIDs(); len(nodes) > 0 && !_u.mutation.TransactionEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionEntriesTable,
			Columns: []string{household.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionEntriesTable,
			Columns: []string{household.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecurringSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.RecurringSubscriptionsTable,
			Columns: []string{household.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecurringSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.RecurringSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.RecurringSubscriptionsTable,
			Columns: []string{household.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.RecurringSubscriptionsTable,
			Columns: []string{household.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotsTable,
			Columns: []string{household.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotsTable,
			Columns: []string{household.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotsTable,
			Columns: []string{household.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotEntriesTable,
			Columns: []string{household.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotEntriesIDs(); len(nodes) > 0 && !_u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotEntriesTable,
			Columns: []string{household.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotEntriesTable,
			Columns: []string{household.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HouseholdCurrenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdCurrenciesTable,
			Columns: []string{household.HouseholdCurrenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHouseholdCurrenciesIDs(); len(nodes) > 0 && !_u.mutation.HouseholdCurrenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdCurrenciesTable,
			Columns: []string{household.HouseholdCurrenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdCurrenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdCurrenciesTable,
			Columns: []string{household.HouseholdCurrenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HouseholdRatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdRatesTable,
			Columns: []string{household.HouseholdRatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHouseholdRatesIDs(); len(nodes) > 0 && !_u.mutation.HouseholdRatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdRatesTable,
			Columns: []string{household.HouseholdRatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdRatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdRatesTable,
			Columns: []string{household.HouseholdRatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserHouseholdsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   household.UserHouseholdsTable,
			Columns: []string{household.UserHouseholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userhousehold.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserHouseholdsIDs(); len(nodes) > 0 && !_u.mutation.UserHouseholdsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   household.UserHouseholdsTable,
			Columns: []string{household.UserHouseholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userhousehold.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserHouseholdsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   household.UserHouseholdsTable,
			Columns: []string{household.UserHouseholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userhousehold.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{household.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HouseholdUpdateOne is the builder for updating a single Household entity.
type HouseholdUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *HouseholdMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *HouseholdUpdateOne) SetUpdateTime(v time.Time) *HouseholdUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *HouseholdUpdateOne) SetName(v string) *HouseholdUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HouseholdUpdateOne) SetNillableName(v *string) *HouseholdUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLocale sets the "locale" field.
func (_u *HouseholdUpdateOne) SetLocale(v string) *HouseholdUpdateOne {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *HouseholdUpdateOne) SetNillableLocale(v *string) *HouseholdUpdateOne {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// SetCurrencyCode sets the "currency_code" field.
func (_u *HouseholdUpdateOne) SetCurrencyCode(v string) *HouseholdUpdateOne {
	_u.mutation.SetCurrencyCode(v)
	return _u
}

// SetNillableCurrencyCode sets the "currency_code" field if the given value is not nil.
func (_u *HouseholdUpdateOne) SetNillableCurrencyCode(v *string) *HouseholdUpdateOne {
	if v != nil {
		_u.SetCurrencyCode(*v)
	}
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *HouseholdUpdateOne) AddUserIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *HouseholdUpdateOne) AddUsers(v ...*User) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *HouseholdUpdateOne) AddAccountIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *HouseholdUpdateOne) AddAccounts(v ...*Account) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *HouseholdUpdateOne) AddTransactionIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *HouseholdUpdateOne) AddTransactions(v ...*Transaction) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddInvestmentIDs adds the "investments" edge to the Investment entity by IDs.
func (_u *HouseholdUpdateOne) AddInvestmentIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddInvestmentIDs(ids...)
	return _u
}

// AddInvestments adds the "investments" edges to the Investment entity.
func (_u *HouseholdUpdateOne) AddInvestments(v ...*Investment) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvestmentIDs(ids...)
}

// AddInvestmentLotIDs adds the "investment_lots" edge to the InvestmentLot entity by IDs.
func (_u *HouseholdUpdateOne) AddInvestmentLotIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddInvestmentLotIDs(ids...)
	return _u
}

// AddInvestmentLots adds the "investment_lots" edges to the InvestmentLot entity.
func (_u *HouseholdUpdateOne) AddInvestmentLots(v ...*InvestmentLot) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvestmentLotIDs(ids...)
}

// AddTransactionCategoryIDs adds the "transaction_categories" edge to the TransactionCategory entity by IDs.
func (_u *HouseholdUpdateOne) AddTransactionCategoryIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddTransactionCategoryIDs(ids...)
	return _u
}

// AddTransactionCategories adds the "transaction_categories" edges to the TransactionCategory entity.
func (_u *HouseholdUpdateOne) AddTransactionCategories(v ...*TransactionCategory) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionCategoryIDs(ids...)
}

// AddTransactionEntryIDs adds the "transaction_entries" edge to the TransactionEntry entity by IDs.
func (_u *HouseholdUpdateOne) AddTransactionEntryIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddTransactionEntryIDs(ids...)
	return _u
}

// AddTransactionEntries adds the "transaction_entries" edges to the TransactionEntry entity.
func (_u *HouseholdUpdateOne) AddTransactionEntries(v ...*TransactionEntry) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionEntryIDs(ids...)
}

// AddRecurringSubscriptionIDs adds the "recurring_subscriptions" edge to the RecurringSubscription entity by IDs.
func (_u *HouseholdUpdateOne) AddRecurringSubscriptionIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddRecurringSubscriptionIDs(ids...)
	return _u
}

// AddRecurringSubscriptions adds the "recurring_subscriptions" edges to the RecurringSubscription entity.
func (_u *HouseholdUpdateOne) AddRecurringSubscriptions(v ...*RecurringSubscription) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecurringSubscriptionIDs(ids...)
}

// AddSnapshotIDs adds the "snapshots" edge to the Snapshot entity by IDs.
func (_u *HouseholdUpdateOne) AddSnapshotIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the Snapshot entity.
func (_u *HouseholdUpdateOne) AddSnapshots(v ...*Snapshot) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddSnapshotEntryIDs adds the "snapshot_entries" edge to the SnapshotEntry entity by IDs.
func (_u *HouseholdUpdateOne) AddSnapshotEntryIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddSnapshotEntryIDs(ids...)
	return _u
}

// AddSnapshotEntries adds the "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *HouseholdUpdateOne) AddSnapshotEntries(v ...*SnapshotEntry) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotEntryIDs(ids...)
}

// AddHouseholdCurrencyIDs adds the "household_currencies" edge to the HouseholdCurrency entity by IDs.
func (_u *HouseholdUpdateOne) AddHouseholdCurrencyIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddHouseholdCurrencyIDs(ids...)
	return _u
}

// AddHouseholdCurrencies adds the "household_currencies" edges to the HouseholdCurrency entity.
func (_u *HouseholdUpdateOne) AddHouseholdCurrencies(v ...*HouseholdCurrency) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHouseholdCurrencyIDs(ids...)
}

// AddHouseholdRateIDs adds the "household_rates" edge to the HouseholdRate entity by IDs.
func (_u *HouseholdUpdateOne) AddHouseholdRateIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddHouseholdRateIDs(ids...)
	return _u
}

// AddHouseholdRates adds the "household_rates" edges to the HouseholdRate entity.
func (_u *HouseholdUpdateOne) AddHouseholdRates(v ...*HouseholdRate) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHouseholdRateIDs(ids...)
}

// AddUserHouseholdIDs adds the "user_households" edge to the UserHousehold entity by IDs.
func (_u *HouseholdUpdateOne) AddUserHouseholdIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.AddUserHouseholdIDs(ids...)
	return _u
}

// AddUserHouseholds adds the "user_households" edges to the UserHousehold entity.
func (_u *HouseholdUpdateOne) AddUserHouseholds(v ...*UserHousehold) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserHouseholdIDs(ids...)
}

// Mutation returns the HouseholdMutation object of the builder.
func (_u *HouseholdUpdateOne) Mutation() *HouseholdMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *HouseholdUpdateOne) ClearUsers() *HouseholdUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *HouseholdUpdateOne) RemoveUserIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *HouseholdUpdateOne) RemoveUsers(v ...*User) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *HouseholdUpdateOne) ClearAccounts() *HouseholdUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *HouseholdUpdateOne) RemoveAccountIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *HouseholdUpdateOne) RemoveAccounts(v ...*Account) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *HouseholdUpdateOne) ClearTransactions() *HouseholdUpdateOne {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *HouseholdUpdateOne) RemoveTransactionIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *HouseholdUpdateOne) RemoveTransactions(v ...*Transaction) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearInvestments clears all "investments" edges to the Investment entity.
func (_u *HouseholdUpdateOne) ClearInvestments() *HouseholdUpdateOne {
	_u.mutation.ClearInvestments()
	return _u
}

// RemoveInvestmentIDs removes the "investments" edge to Investment entities by IDs.
func (_u *HouseholdUpdateOne) RemoveInvestmentIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveInvestmentIDs(ids...)
	return _u
}

// RemoveInvestments removes "investments" edges to Investment entities.
func (_u *HouseholdUpdateOne) RemoveInvestments(v ...*Investment) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvestmentIDs(ids...)
}

// ClearInvestmentLots clears all "investment_lots" edges to the InvestmentLot entity.
func (_u *HouseholdUpdateOne) ClearInvestmentLots() *HouseholdUpdateOne {
	_u.mutation.ClearInvestmentLots()
	return _u
}

// RemoveInvestmentLotIDs removes the "investment_lots" edge to InvestmentLot entities by IDs.
func (_u *HouseholdUpdateOne) RemoveInvestmentLotIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveInvestmentLotIDs(ids...)
	return _u
}

// RemoveInvestmentLots removes "investment_lots" edges to InvestmentLot entities.
func (_u *HouseholdUpdateOne) RemoveInvestmentLots(v ...*InvestmentLot) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvestmentLotIDs(ids...)
}

// ClearTransactionCategories clears all "transaction_categories" edges to the TransactionCategory entity.
func (_u *HouseholdUpdateOne) ClearTransactionCategories() *HouseholdUpdateOne {
	_u.mutation.ClearTransactionCategories()
	return _u
}

// RemoveTransactionCategoryIDs removes the "transaction_categories" edge to TransactionCategory entities by IDs.
func (_u *HouseholdUpdateOne) RemoveTransactionCategoryIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveTransactionCategoryIDs(ids...)
	return _u
}

// RemoveTransactionCategories removes "transaction_categories" edges to TransactionCategory entities.
func (_u *HouseholdUpdateOne) RemoveTransactionCategories(v ...*TransactionCategory) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionCategoryIDs(ids...)
}

// ClearTransactionEntries clears all "transaction_entries" edges to the TransactionEntry entity.
func (_u *HouseholdUpdateOne) ClearTransactionEntries() *HouseholdUpdateOne {
	_u.mutation.ClearTransactionEntries()
	return _u
}

// RemoveTransactionEntryIDs removes the "transaction_entries" edge to TransactionEntry entities by IDs.
func (_u *HouseholdUpdateOne) RemoveTransactionEntryIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveTransactionEntryIDs(ids...)
	return _u
}

// RemoveTransactionEntries removes "transaction_entries" edges to TransactionEntry entities.
func (_u *HouseholdUpdateOne) RemoveTransactionEntries(v ...*TransactionEntry) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionEntryIDs(ids...)
}

// ClearRecurringSubscriptions clears all "recurring_subscriptions" edges to the RecurringSubscription entity.
func (_u *HouseholdUpdateOne) ClearRecurringSubscriptions() *HouseholdUpdateOne {
	_u.mutation.ClearRecurringSubscriptions()
	return _u
}

// RemoveRecurringSubscriptionIDs removes the "recurring_subscriptions" edge to RecurringSubscription entities by IDs.
func (_u *HouseholdUpdateOne) RemoveRecurringSubscriptionIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveRecurringSubscriptionIDs(ids...)
	return _u
}

// RemoveRecurringSubscriptions removes "recurring_subscriptions" edges to RecurringSubscription entities.
func (_u *HouseholdUpdateOne) RemoveRecurringSubscriptions(v ...*RecurringSubscription) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecurringSubscriptionIDs(ids...)
}

// ClearSnapshots clears all "snapshots" edges to the Snapshot entity.
func (_u *HouseholdUpdateOne) ClearSnapshots() *HouseholdUpdateOne {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to Snapshot entities by IDs.
func (_u *HouseholdUpdateOne) RemoveSnapshotIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to Snapshot entities.
func (_u *HouseholdUpdateOne) RemoveSnapshots(v ...*Snapshot) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearSnapshotEntries clears all "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *HouseholdUpdateOne) ClearSnapshotEntries() *HouseholdUpdateOne {
	_u.mutation.ClearSnapshotEntries()
	return _u
}

// RemoveSnapshotEntryIDs removes the "snapshot_entries" edge to SnapshotEntry entities by IDs.
func (_u *HouseholdUpdateOne) RemoveSnapshotEntryIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveSnapshotEntryIDs(ids...)
	return _u
}

// RemoveSnapshotEntries removes "snapshot_entries" edges to SnapshotEntry entities.
func (_u *HouseholdUpdateOne) RemoveSnapshotEntries(v ...*SnapshotEntry) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotEntryIDs(ids...)
}

// ClearHouseholdCurrencies clears all "household_currencies" edges to the HouseholdCurrency entity.
func (_u *HouseholdUpdateOne) ClearHouseholdCurrencies() *HouseholdUpdateOne {
	_u.mutation.ClearHouseholdCurrencies()
	return _u
}

// RemoveHouseholdCurrencyIDs removes the "household_currencies" edge to HouseholdCurrency entities by IDs.
func (_u *HouseholdUpdateOne) RemoveHouseholdCurrencyIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveHouseholdCurrencyIDs(ids...)
	return _u
}

// RemoveHouseholdCurrencies removes "household_currencies" edges to HouseholdCurrency entities.
func (_u *HouseholdUpdateOne) RemoveHouseholdCurrencies(v ...*HouseholdCurrency) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHouseholdCurrencyIDs(ids...)
}

// ClearHouseholdRates clears all "household_rates" edges to the HouseholdRate entity.
func (_u *HouseholdUpdateOne) ClearHouseholdRates() *HouseholdUpdateOne {
	_u.mutation.ClearHouseholdRates()
	return _u
}

// RemoveHouseholdRateIDs removes the "household_rates" edge to HouseholdRate entities by IDs.
func (_u *HouseholdUpdateOne) RemoveHouseholdRateIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveHouseholdRateIDs(ids...)
	return _u
}

// RemoveHouseholdRates removes "household_rates" edges to HouseholdRate entities.
func (_u *HouseholdUpdateOne) RemoveHouseholdRates(v ...*HouseholdRate) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHouseholdRateIDs(ids...)
}

// ClearUserHouseholds clears all "user_households" edges to the UserHousehold entity.
func (_u *HouseholdUpdateOne) ClearUserHouseholds() *HouseholdUpdateOne {
	_u.mutation.ClearUserHouseholds()
	return _u
}

// RemoveUserHouseholdIDs removes the "user_households" edge to UserHousehold entities by IDs.
func (_u *HouseholdUpdateOne) RemoveUserHouseholdIDs(ids ...int) *HouseholdUpdateOne {
	_u.mutation.RemoveUserHouseholdIDs(ids...)
	return _u
}

// RemoveUserHouseholds removes "user_households" edges to UserHousehold entities.
func (_u *HouseholdUpdateOne) RemoveUserHouseholds(v ...*UserHousehold) *HouseholdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserHouseholdIDs(ids...)
}

// Where appends a list predicates to the HouseholdUpdate builder.
func (_u *HouseholdUpdateOne) Where(ps ...predicate.Household) *HouseholdUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HouseholdUpdateOne) Select(field string, fields ...string) *HouseholdUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Household entity.
func (_u *HouseholdUpdateOne) Save(ctx context.Context) (*Household, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HouseholdUpdateOne) SaveX(ctx context.Context) *Household {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HouseholdUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HouseholdUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HouseholdUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if household.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized household.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := household.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *HouseholdUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := household.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Household.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locale(); ok {
		if err := household.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "Household.locale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrencyCode(); ok {
		if err := household.CurrencyCodeValidator(v); err != nil {
			return &ValidationError{Name: "currency_code", err: fmt.Errorf(`ent: validator failed for field "Household.currency_code": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HouseholdUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HouseholdUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HouseholdUpdateOne) sqlSave(ctx context.Context) (_node *Household, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(household.Table, household.Columns, sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Household.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, household.FieldID)
		for _, f := range fields {
			if !household.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != household.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(household.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(household.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(household.FieldLocale, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrencyCode(); ok {
		_spec.SetField(household.FieldCurrencyCode, field.TypeString, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   household.UsersTable,
			Columns: household.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		createE := &UserHouseholdCreate{config: _u.config, mutation: newUserHouseholdMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   household.UsersTable,
			Columns: household.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserHouseholdCreate{config: _u.config, mutation: newUserHouseholdMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   household.UsersTable,
			Columns: household.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserHouseholdCreate{config: _u.config, mutation: newUserHouseholdMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.AccountsTable,
			Columns: []string{household.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.AccountsTable,
			Columns: []string{household.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.AccountsTable,
			Columns: []string{household.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionsTable,
			Columns: []string{household.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionsTable,
			Columns: []string{household.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionsTable,
			Columns: []string{household.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvestmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentsTable,
			Columns: []string{household.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvestmentsIDs(); len(nodes) > 0 && !_u.mutation.InvestmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentsTable,
			Columns: []string{household.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvestmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentsTable,
			Columns: []string{household.InvestmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvestmentLotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentLotsTable,
			Columns: []string{household.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvestmentLotsIDs(); len(nodes) > 0 && !_u.mutation.InvestmentLotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentLotsTable,
			Columns: []string{household.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvestmentLotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.InvestmentLotsTable,
			Columns: []string{household.InvestmentLotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investmentlot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionCategoriesTable,
			Columns: []string{household.TransactionCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactioncategory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionCategoriesIDs(); len(nodes) > 0 && !_u.mutation.TransactionCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionCategoriesTable,
			Columns: []string{household.TransactionCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactioncategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionCategoriesTable,
			Columns: []string{household.TransactionCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactioncategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionEntriesTable,
			Columns: []string{household.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionEntriesIDs(); len(nodes) > 0 && !_u.mutation.TransactionEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionEntriesTable,
			Columns: []string{household.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.TransactionEntriesTable,
			Columns: []string{household.TransactionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecurringSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.RecurringSubscriptionsTable,
			Columns: []string{household.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecurringSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.RecurringSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.RecurringSubscriptionsTable,
			Columns: []string{household.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecurringSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.RecurringSubscriptionsTable,
			Columns: []string{household.RecurringSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringsubscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotsTable,
			Columns: []string{household.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotsTable,
			Columns: []string{household.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotsTable,
			Columns: []string{household.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotEntriesTable,
			Columns: []string{household.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotEntriesIDs(); len(nodes) > 0 && !_u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotEntriesTable,
			Columns: []string{household.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.SnapshotEntriesTable,
			Columns: []string{household.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HouseholdCurrenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdCurrenciesTable,
			Columns: []string{household.HouseholdCurrenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHouseholdCurrenciesIDs(); len(nodes) > 0 && !_u.mutation.HouseholdCurrenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdCurrenciesTable,
			Columns: []string{household.HouseholdCurrenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdCurrenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdCurrenciesTable,
			Columns: []string{household.HouseholdCurrenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HouseholdRatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdRatesTable,
			Columns: []string{household.HouseholdRatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHouseholdRatesIDs(); len(nodes) > 0 && !_u.mutation.HouseholdRatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdRatesTable,
			Columns: []string{household.HouseholdRatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HouseholdRatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   household.HouseholdRatesTable,
			Columns: []string{household.HouseholdRatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserHouseholdsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   household.UserHouseholdsTable,
			Columns: []string{household.UserHouseholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userhousehold.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserHouseholdsIDs(); len(nodes) > 0 && !_u.mutation.UserHouseholdsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   household.UserHouseholdsTable,
			Columns: []string{household.UserHouseholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userhousehold.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserHouseholdsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   household.UserHouseholdsTable,
			Columns: []string{household.UserHouseholdsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userhousehold.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Household{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{household.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
