// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"beavermoney.app/ent/household"
	"beavermoney.app/ent/householdcurrency"
	"beavermoney.app/ent/householdrate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
)

// HouseholdRateCreate is the builder for creating a HouseholdRate entity.
type HouseholdRateCreate struct {
	config
	mutation *HouseholdRateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetHouseholdID sets the "household_id" field.
func (_c *HouseholdRateCreate) SetHouseholdID(v int) *HouseholdRateCreate {
	_c.mutation.SetHouseholdID(v)
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *HouseholdRateCreate) SetCreateTime(v time.Time) *HouseholdRateCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *HouseholdRateCreate) SetNillableCreateTime(v *time.Time) *HouseholdRateCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *HouseholdRateCreate) SetUpdateTime(v time.Time) *HouseholdRateCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *HouseholdRateCreate) SetNillableUpdateTime(v *time.Time) *HouseholdRateCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetRate sets the "rate" field.
func (_c *HouseholdRateCreate) SetRate(v decimal.Decimal) *HouseholdRateCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetFromHouseholdCurrencyID sets the "from_household_currency_id" field.
func (_c *HouseholdRateCreate) SetFromHouseholdCurrencyID(v int) *HouseholdRateCreate {
	_c.mutation.SetFromHouseholdCurrencyID(v)
	return _c
}

// SetLegacyFromCurrencyID sets the "legacy_from_currency_id" field.
func (_c *HouseholdRateCreate) SetLegacyFromCurrencyID(v int) *HouseholdRateCreate {
	_c.mutation.SetLegacyFromCurrencyID(v)
	return _c
}

// SetNillableLegacyFromCurrencyID sets the "legacy_from_currency_id" field if the given value is not nil.
func (_c *HouseholdRateCreate) SetNillableLegacyFromCurrencyID(v *int) *HouseholdRateCreate {
	if v != nil {
		_c.SetLegacyFromCurrencyID(*v)
	}
	return _c
}

// SetToHouseholdCurrencyID sets the "to_household_currency_id" field.
func (_c *HouseholdRateCreate) SetToHouseholdCurrencyID(v int) *HouseholdRateCreate {
	_c.mutation.SetToHouseholdCurrencyID(v)
	return _c
}

// SetLegacyToCurrencyID sets the "legacy_to_currency_id" field.
func (_c *HouseholdRateCreate) SetLegacyToCurrencyID(v int) *HouseholdRateCreate {
	_c.mutation.SetLegacyToCurrencyID(v)
	return _c
}

// SetNillableLegacyToCurrencyID sets the "legacy_to_currency_id" field if the given value is not nil.
func (_c *HouseholdRateCreate) SetNillableLegacyToCurrencyID(v *int) *HouseholdRateCreate {
	if v != nil {
		_c.SetLegacyToCurrencyID(*v)
	}
	return _c
}

// SetHousehold sets the "household" edge to the Household entity.
func (_c *HouseholdRateCreate) SetHousehold(v *Household) *HouseholdRateCreate {
	return _c.SetHouseholdID(v.ID)
}

// SetFromCurrencyID sets the "from_currency" edge to the HouseholdCurrency entity by ID.
func (_c *HouseholdRateCreate) SetFromCurrencyID(id int) *HouseholdRateCreate {
	_c.mutation.SetFromCurrencyID(id)
	return _c
}

// SetFromCurrency sets the "from_currency" edge to the HouseholdCurrency entity.
func (_c *HouseholdRateCreate) SetFromCurrency(v *HouseholdCurrency) *HouseholdRateCreate {
	return _c.SetFromCurrencyID(v.ID)
}

// SetToCurrencyID sets the "to_currency" edge to the HouseholdCurrency entity by ID.
func (_c *HouseholdRateCreate) SetToCurrencyID(id int) *HouseholdRateCreate {
	_c.mutation.SetToCurrencyID(id)
	return _c
}

// SetToCurrency sets the "to_currency" edge to the HouseholdCurrency entity.
func (_c *HouseholdRateCreate) SetToCurrency(v *HouseholdCurrency) *HouseholdRateCreate {
	return _c.SetToCurrencyID(v.ID)
}

// Mutation returns the HouseholdRateMutation object of the builder.
func (_c *HouseholdRateCreate) Mutation() *HouseholdRateMutation {
	return _c.mutation
}

// Save creates the HouseholdRate in the database.
func (_c *HouseholdRateCreate) Save(ctx context.Context) (*HouseholdRate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HouseholdRateCreate) SaveX(ctx context.Context) *HouseholdRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HouseholdRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HouseholdRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HouseholdRateCreate) defaults() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		if householdrate.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized householdrate.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := householdrate.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		if householdrate.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized householdrate.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := householdrate.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *HouseholdRateCreate) check() error {
	if _, ok := _c.mutation.HouseholdID(); !ok {
		return &ValidationError{Name: "household_id", err: errors.New(`ent: missing required field "HouseholdRate.household_id"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "HouseholdRate.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "HouseholdRate.update_time"`)}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "HouseholdRate.rate"`)}
	}
	if _, ok := _c.mutation.FromHouseholdCurrencyID(); !ok {
		return &ValidationError{Name: "from_household_currency_id", err: errors.New(`ent: missing required field "HouseholdRate.from_household_currency_id"`)}
	}
	if v, ok := _c.mutation.FromHouseholdCurrencyID(); ok {
		if err := householdrate.FromHouseholdCurrencyIDValidator(v); err != nil {
			return &ValidationError{Name: "from_household_currency_id", err: fmt.Errorf(`ent: validator failed for field "HouseholdRate.from_household_currency_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToHouseholdCurrencyID(); !ok {
		return &ValidationError{Name: "to_household_currency_id", err: errors.New(`ent: missing required field "HouseholdRate.to_household_currency_id"`)}
	}
	if v, ok := _c.mutation.ToHouseholdCurrencyID(); ok {
		if err := householdrate.ToHouseholdCurrencyIDValidator(v); err != nil {
			return &ValidationError{Name: "to_household_currency_id", err: fmt.Errorf(`ent: validator failed for field "HouseholdRate.to_household_currency_id": %w`, err)}
		}
	}
	if len(_c.mutation.HouseholdIDs()) == 0 {
		return &ValidationError{Name: "household", err: errors.New(`ent: missing required edge "HouseholdRate.household"`)}
	}
	if len(_c.mutation.FromCurrencyIDs()) == 0 {
		return &ValidationError{Name: "from_currency", err: errors.New(`ent: missing required edge "HouseholdRate.from_currency"`)}
	}
	if len(_c.mutation.ToCurrencyIDs()) == 0 {
		return &ValidationError{Name: "to_currency", err: errors.New(`ent: missing required edge "HouseholdRate.to_currency"`)}
	}
	return nil
}

func (_c *HouseholdRateCreate) sqlSave(ctx context.Context) (*HouseholdRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HouseholdRateCreate) createSpec() (*HouseholdRate, *sqlgraph.CreateSpec) {
	var (
		_node = &HouseholdRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(householdrate.Table, sqlgraph.NewFieldSpec(householdrate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(householdrate.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(householdrate.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(householdrate.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	if value, ok := _c.mutation.LegacyFromCurrencyID(); ok {
		_spec.SetField(householdrate.FieldLegacyFromCurrencyID, field.TypeInt, value)
		_node.LegacyFromCurrencyID = &value
	}
	if value, ok := _c.mutation.LegacyToCurrencyID(); ok {
		_spec.SetField(householdrate.FieldLegacyToCurrencyID, field.TypeInt, value)
		_node.LegacyToCurrencyID = &value
	}
	if nodes := _c.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   householdrate.HouseholdTable,
			Columns: []string{householdrate.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HouseholdID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FromCurrencyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   householdrate.FromCurrencyTable,
			Columns: []string{householdrate.FromCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FromHouseholdCurrencyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ToCurrencyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   householdrate.ToCurrencyTable,
			Columns: []string{householdrate.ToCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ToHouseholdCurrencyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HouseholdRate.Create().
//		SetHouseholdID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HouseholdRateUpsert) {
//			SetHouseholdID(v+v).
//		}).
//		Exec(ctx)
func (_c *HouseholdRateCreate) OnConflict(opts ...sql.ConflictOption) *HouseholdRateUpsertOne {
	_c.conflict = opts
	return &HouseholdRateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HouseholdRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HouseholdRateCreate) OnConflictColumns(columns ...string) *HouseholdRateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HouseholdRateUpsertOne{
		create: _c,
	}
}

type (
	// HouseholdRateUpsertOne is the builder for "upsert"-ing
	//  one HouseholdRate node.
	HouseholdRateUpsertOne struct {
		create *HouseholdRateCreate
	}

	// HouseholdRateUpsert is the "OnConflict" setter.
	HouseholdRateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *HouseholdRateUpsert) SetUpdateTime(v time.Time) *HouseholdRateUpsert {
	u.Set(householdrate.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *HouseholdRateUpsert) UpdateUpdateTime() *HouseholdRateUpsert {
	u.SetExcluded(householdrate.FieldUpdateTime)
	return u
}

// SetRate sets the "rate" field.
func (u *HouseholdRateUpsert) SetRate(v decimal.Decimal) *HouseholdRateUpsert {
	u.Set(householdrate.FieldRate, v)
	return u
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *HouseholdRateUpsert) UpdateRate() *HouseholdRateUpsert {
	u.SetExcluded(householdrate.FieldRate)
	return u
}

// AddRate adds v to the "rate" field.
func (u *HouseholdRateUpsert) AddRate(v decimal.Decimal) *HouseholdRateUpsert {
	u.Add(householdrate.FieldRate, v)
	return u
}

// SetLegacyFromCurrencyID sets the "legacy_from_currency_id" field.
func (u *HouseholdRateUpsert) SetLegacyFromCurrencyID(v int) *HouseholdRateUpsert {
	u.Set(householdrate.FieldLegacyFromCurrencyID, v)
	return u
}

// UpdateLegacyFromCurrencyID sets the "legacy_from_currency_id" field to the value that was provided on create.
func (u *HouseholdRateUpsert) UpdateLegacyFromCurrencyID() *HouseholdRateUpsert {
	u.SetExcluded(householdrate.FieldLegacyFromCurrencyID)
	return u
}

// AddLegacyFromCurrencyID adds v to the "legacy_from_currency_id" field.
func (u *HouseholdRateUpsert) AddLegacyFromCurrencyID(v int) *HouseholdRateUpsert {
	u.Add(householdrate.FieldLegacyFromCurrencyID, v)
	return u
}

// ClearLegacyFromCurrencyID clears the value of the "legacy_from_currency_id" field.
func (u *HouseholdRateUpsert) ClearLegacyFromCurrencyID() *HouseholdRateUpsert {
	u.SetNull(householdrate.FieldLegacyFromCurrencyID)
	return u
}

// SetLegacyToCurrencyID sets the "legacy_to_currency_id" field.
func (u *HouseholdRateUpsert) SetLegacyToCurrencyID(v int) *HouseholdRateUpsert {
	u.Set(householdrate.FieldLegacyToCurrencyID, v)
	return u
}

// UpdateLegacyToCurrencyID sets the "legacy_to_currency_id" field to the value that was provided on create.
func (u *HouseholdRateUpsert) UpdateLegacyToCurrencyID() *HouseholdRateUpsert {
	u.SetExcluded(householdrate.FieldLegacyToCurrencyID)
	return u
}

// AddLegacyToCurrencyID adds v to the "legacy_to_currency_id" field.
func (u *HouseholdRateUpsert) AddLegacyToCurrencyID(v int) *HouseholdRateUpsert {
	u.Add(householdrate.FieldLegacyToCurrencyID, v)
	return u
}

// ClearLegacyToCurrencyID clears the value of the "legacy_to_currency_id" field.
func (u *HouseholdRateUpsert) ClearLegacyToCurrencyID() *HouseholdRateUpsert {
	u.SetNull(householdrate.FieldLegacyToCurrencyID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.HouseholdRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HouseholdRateUpsertOne) UpdateNewValues() *HouseholdRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.HouseholdID(); exists {
			s.SetIgnore(householdrate.FieldHouseholdID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(householdrate.FieldCreateTime)
		}
		if _, exists := u.create.mutation.FromHouseholdCurrencyID(); exists {
			s.SetIgnore(householdrate.FieldFromHouseholdCurrencyID)
		}
		if _, exists := u.create.mutation.ToHouseholdCurrencyID(); exists {
			s.SetIgnore(householdrate.FieldToHouseholdCurrencyID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HouseholdRate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HouseholdRateUpsertOne) Ignore() *HouseholdRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HouseholdRateUpsertOne) DoNothing() *HouseholdRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HouseholdRateCreate.OnConflict
// documentation for more info.
func (u *HouseholdRateUpsertOne) Update(set func(*HouseholdRateUpsert)) *HouseholdRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HouseholdRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *HouseholdRateUpsertOne) SetUpdateTime(v time.Time) *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *HouseholdRateUpsertOne) UpdateUpdateTime() *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetRate sets the "rate" field.
func (u *HouseholdRateUpsertOne) SetRate(v decimal.Decimal) *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *HouseholdRateUpsertOne) AddRate(v decimal.Decimal) *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *HouseholdRateUpsertOne) UpdateRate() *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.UpdateRate()
	})
}

// SetLegacyFromCurrencyID sets the "legacy_from_currency_id" field.
func (u *HouseholdRateUpsertOne) SetLegacyFromCurrencyID(v int) *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.SetLegacyFromCurrencyID(v)
	})
}

// AddLegacyFromCurrencyID adds v to the "legacy_from_currency_id" field.
func (u *HouseholdRateUpsertOne) AddLegacyFromCurrencyID(v int) *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.AddLegacyFromCurrencyID(v)
	})
}

// UpdateLegacyFromCurrencyID sets the "legacy_from_currency_id" field to the value that was provided on create.
func (u *HouseholdRateUpsertOne) UpdateLegacyFromCurrencyID() *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.UpdateLegacyFromCurrencyID()
	})
}

// ClearLegacyFromCurrencyID clears the value of the "legacy_from_currency_id" field.
func (u *HouseholdRateUpsertOne) ClearLegacyFromCurrencyID() *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.ClearLegacyFromCurrencyID()
	})
}

// SetLegacyToCurrencyID sets the "legacy_to_currency_id" field.
func (u *HouseholdRateUpsertOne) SetLegacyToCurrencyID(v int) *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.SetLegacyToCurrencyID(v)
	})
}

// AddLegacyToCurrencyID adds v to the "legacy_to_currency_id" field.
func (u *HouseholdRateUpsertOne) AddLegacyToCurrencyID(v int) *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.AddLegacyToCurrencyID(v)
	})
}

// UpdateLegacyToCurrencyID sets the "legacy_to_currency_id" field to the value that was provided on create.
func (u *HouseholdRateUpsertOne) UpdateLegacyToCurrencyID() *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.UpdateLegacyToCurrencyID()
	})
}

// ClearLegacyToCurrencyID clears the value of the "legacy_to_currency_id" field.
func (u *HouseholdRateUpsertOne) ClearLegacyToCurrencyID() *HouseholdRateUpsertOne {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.ClearLegacyToCurrencyID()
	})
}

// Exec executes the query.
func (u *HouseholdRateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HouseholdRateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HouseholdRateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HouseholdRateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HouseholdRateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HouseholdRateCreateBulk is the builder for creating many HouseholdRate entities in bulk.
type HouseholdRateCreateBulk struct {
	config
	err      error
	builders []*HouseholdRateCreate
	conflict []sql.ConflictOption
}

// Save creates the HouseholdRate entities in the database.
func (_c *HouseholdRateCreateBulk) Save(ctx context.Context) ([]*HouseholdRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HouseholdRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HouseholdRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HouseholdRateCreateBulk) SaveX(ctx context.Context) []*HouseholdRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HouseholdRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HouseholdRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HouseholdRate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HouseholdRateUpsert) {
//			SetHouseholdID(v+v).
//		}).
//		Exec(ctx)
func (_c *HouseholdRateCreateBulk) OnConflict(opts ...sql.ConflictOption) *HouseholdRateUpsertBulk {
	_c.conflict = opts
	return &HouseholdRateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HouseholdRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HouseholdRateCreateBulk) OnConflictColumns(columns ...string) *HouseholdRateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HouseholdRateUpsertBulk{
		create: _c,
	}
}

// HouseholdRateUpsertBulk is the builder for "upsert"-ing
// a bulk of HouseholdRate nodes.
type HouseholdRateUpsertBulk struct {
	create *HouseholdRateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HouseholdRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HouseholdRateUpsertBulk) UpdateNewValues() *HouseholdRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.HouseholdID(); exists {
				s.SetIgnore(householdrate.FieldHouseholdID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(householdrate.FieldCreateTime)
			}
			if _, exists := b.mutation.FromHouseholdCurrencyID(); exists {
				s.SetIgnore(householdrate.FieldFromHouseholdCurrencyID)
			}
			if _, exists := b.mutation.ToHouseholdCurrencyID(); exists {
				s.SetIgnore(householdrate.FieldToHouseholdCurrencyID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HouseholdRate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HouseholdRateUpsertBulk) Ignore() *HouseholdRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HouseholdRateUpsertBulk) DoNothing() *HouseholdRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HouseholdRateCreateBulk.OnConflict
// documentation for more info.
func (u *HouseholdRateUpsertBulk) Update(set func(*HouseholdRateUpsert)) *HouseholdRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HouseholdRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *HouseholdRateUpsertBulk) SetUpdateTime(v time.Time) *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *HouseholdRateUpsertBulk) UpdateUpdateTime() *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetRate sets the "rate" field.
func (u *HouseholdRateUpsertBulk) SetRate(v decimal.Decimal) *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *HouseholdRateUpsertBulk) AddRate(v decimal.Decimal) *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *HouseholdRateUpsertBulk) UpdateRate() *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.UpdateRate()
	})
}

// SetLegacyFromCurrencyID sets the "legacy_from_currency_id" field.
func (u *HouseholdRateUpsertBulk) SetLegacyFromCurrencyID(v int) *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.SetLegacyFromCurrencyID(v)
	})
}

// AddLegacyFromCurrencyID adds v to the "legacy_from_currency_id" field.
func (u *HouseholdRateUpsertBulk) AddLegacyFromCurrencyID(v int) *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.AddLegacyFromCurrencyID(v)
	})
}

// UpdateLegacyFromCurrencyID sets the "legacy_from_currency_id" field to the value that was provided on create.
func (u *HouseholdRateUpsertBulk) UpdateLegacyFromCurrencyID() *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.UpdateLegacyFromCurrencyID()
	})
}

// ClearLegacyFromCurrencyID clears the value of the "legacy_from_currency_id" field.
func (u *HouseholdRateUpsertBulk) ClearLegacyFromCurrencyID() *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.ClearLegacyFromCurrencyID()
	})
}

// SetLegacyToCurrencyID sets the "legacy_to_currency_id" field.
func (u *HouseholdRateUpsertBulk) SetLegacyToCurrencyID(v int) *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.SetLegacyToCurrencyID(v)
	})
}

// AddLegacyToCurrencyID adds v to the "legacy_to_currency_id" field.
func (u *HouseholdRateUpsertBulk) AddLegacyToCurrencyID(v int) *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.AddLegacyToCurrencyID(v)
	})
}

// UpdateLegacyToCurrencyID sets the "legacy_to_currency_id" field to the value that was provided on create.
func (u *HouseholdRateUpsertBulk) UpdateLegacyToCurrencyID() *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.UpdateLegacyToCurrencyID()
	})
}

// ClearLegacyToCurrencyID clears the value of the "legacy_to_currency_id" field.
func (u *HouseholdRateUpsertBulk) ClearLegacyToCurrencyID() *HouseholdRateUpsertBulk {
	return u.Update(func(s *HouseholdRateUpsert) {
		s.ClearLegacyToCurrencyID()
	})
}

// Exec executes the query.
func (u *HouseholdRateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HouseholdRateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HouseholdRateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HouseholdRateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
