// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"beavermoney.app/ent/currency"
	"beavermoney.app/ent/household"
	"beavermoney.app/ent/householdcurrency"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// HouseholdCurrency is the model entity for the HouseholdCurrency schema.
type HouseholdCurrency struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// HouseholdID holds the value of the "household_id" field.
	HouseholdID int `json:"household_id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Important holds the value of the "important" field.
	Important bool `json:"important,omitempty"`
	// CurrencyID holds the value of the "currency_id" field.
	CurrencyID int `json:"currency_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HouseholdCurrencyQuery when eager-loading is set.
	Edges        HouseholdCurrencyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// HouseholdCurrencyEdges holds the relations/edges for other nodes in the graph.
type HouseholdCurrencyEdges struct {
	// Household holds the value of the household edge.
	Household *Household `json:"household,omitempty"`
	// Currency holds the value of the currency edge.
	Currency *Currency `json:"currency,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// HouseholdOrErr returns the Household value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HouseholdCurrencyEdges) HouseholdOrErr() (*Household, error) {
	if e.Household != nil {
		return e.Household, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: household.Label}
	}
	return nil, &NotLoadedError{edge: "household"}
}

// CurrencyOrErr returns the Currency value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HouseholdCurrencyEdges) CurrencyOrErr() (*Currency, error) {
	if e.Currency != nil {
		return e.Currency, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: currency.Label}
	}
	return nil, &NotLoadedError{edge: "currency"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HouseholdCurrency) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case householdcurrency.FieldImportant:
			values[i] = new(sql.NullBool)
		case householdcurrency.FieldID, householdcurrency.FieldHouseholdID, householdcurrency.FieldCurrencyID:
			values[i] = new(sql.NullInt64)
		case householdcurrency.FieldCreateTime, householdcurrency.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HouseholdCurrency fields.
func (_m *HouseholdCurrency) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case householdcurrency.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case householdcurrency.FieldHouseholdID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field household_id", values[i])
			} else if value.Valid {
				_m.HouseholdID = int(value.Int64)
			}
		case householdcurrency.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case householdcurrency.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case householdcurrency.FieldImportant:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field important", values[i])
			} else if value.Valid {
				_m.Important = value.Bool
			}
		case householdcurrency.FieldCurrencyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field currency_id", values[i])
			} else if value.Valid {
				_m.CurrencyID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HouseholdCurrency.
// This includes values selected through modifiers, order, etc.
func (_m *HouseholdCurrency) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHousehold queries the "household" edge of the HouseholdCurrency entity.
func (_m *HouseholdCurrency) QueryHousehold() *HouseholdQuery {
	return NewHouseholdCurrencyClient(_m.config).QueryHousehold(_m)
}

// QueryCurrency queries the "currency" edge of the HouseholdCurrency entity.
func (_m *HouseholdCurrency) QueryCurrency() *CurrencyQuery {
	return NewHouseholdCurrencyClient(_m.config).QueryCurrency(_m)
}

// Update returns a builder for updating this HouseholdCurrency.
// Note that you need to call HouseholdCurrency.Unwrap() before calling this method if this HouseholdCurrency
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HouseholdCurrency) Update() *HouseholdCurrencyUpdateOne {
	return NewHouseholdCurrencyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HouseholdCurrency entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HouseholdCurrency) Unwrap() *HouseholdCurrency {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HouseholdCurrency is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HouseholdCurrency) String() string {
	var builder strings.Builder
	builder.WriteString("HouseholdCurrency(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("household_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HouseholdID))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("important=")
	builder.WriteString(fmt.Sprintf("%v", _m.Important))
	builder.WriteString(", ")
	builder.WriteString("currency_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrencyID))
	builder.WriteByte(')')
	return builder.String()
}

// HouseholdCurrencies is a parsable slice of HouseholdCurrency.
type HouseholdCurrencies []*HouseholdCurrency
