// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"beavermoney.app/ent/predicate"
	"beavermoney.app/ent/snapshot"
	"beavermoney.app/ent/snapshotentry"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SnapshotUpdate is the builder for updating Snapshot entities.
type SnapshotUpdate struct {
	config
	hooks     []Hook
	mutation  *SnapshotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SnapshotUpdate builder.
func (_u *SnapshotUpdate) Where(ps ...predicate.Snapshot) *SnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SnapshotUpdate) SetUpdateTime(v time.Time) *SnapshotUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *SnapshotUpdate) SetNote(v string) *SnapshotUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *SnapshotUpdate) SetNillableNote(v *string) *SnapshotUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *SnapshotUpdate) ClearNote() *SnapshotUpdate {
	_u.mutation.ClearNote()
	return _u
}

// AddSnapshotEntryIDs adds the "snapshot_entries" edge to the SnapshotEntry entity by IDs.
func (_u *SnapshotUpdate) AddSnapshotEntryIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.AddSnapshotEntryIDs(ids...)
	return _u
}

// AddSnapshotEntries adds the "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *SnapshotUpdate) AddSnapshotEntries(v ...*SnapshotEntry) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotEntryIDs(ids...)
}

// Mutation returns the SnapshotMutation object of the builder.
func (_u *SnapshotUpdate) Mutation() *SnapshotMutation {
	return _u.mutation
}

// ClearSnapshotEntries clears all "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *SnapshotUpdate) ClearSnapshotEntries() *SnapshotUpdate {
	_u.mutation.ClearSnapshotEntries()
	return _u
}

// RemoveSnapshotEntryIDs removes the "snapshot_entries" edge to SnapshotEntry entities by IDs.
func (_u *SnapshotUpdate) RemoveSnapshotEntryIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.RemoveSnapshotEntryIDs(ids...)
	return _u
}

// RemoveSnapshotEntries removes "snapshot_entries" edges to SnapshotEntry entities.
func (_u *SnapshotUpdate) RemoveSnapshotEntries(v ...*SnapshotEntry) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SnapshotUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SnapshotUpdate) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if snapshot.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized snapshot.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := snapshot.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SnapshotUpdate) check() error {
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Snapshot.household"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SnapshotUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SnapshotUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(snapshot.Table, snapshot.Columns, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(snapshot.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(snapshot.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(snapshot.FieldNote, field.TypeString)
	}
	if _u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.SnapshotEntriesTable,
			Columns: []string{snapshot.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotEntriesIDs(); len(nodes) > 0 && !_u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.SnapshotEntriesTable,
			Columns: []string{snapshot.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.SnapshotEntriesTable,
			Columns: []string{snapshot.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SnapshotUpdateOne is the builder for updating a single Snapshot entity.
type SnapshotUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SnapshotMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *SnapshotUpdateOne) SetUpdateTime(v time.Time) *SnapshotUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *SnapshotUpdateOne) SetNote(v string) *SnapshotUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *SnapshotUpdateOne) SetNillableNote(v *string) *SnapshotUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *SnapshotUpdateOne) ClearNote() *SnapshotUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// AddSnapshotEntryIDs adds the "snapshot_entries" edge to the SnapshotEntry entity by IDs.
func (_u *SnapshotUpdateOne) AddSnapshotEntryIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.AddSnapshotEntryIDs(ids...)
	return _u
}

// AddSnapshotEntries adds the "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *SnapshotUpdateOne) AddSnapshotEntries(v ...*SnapshotEntry) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotEntryIDs(ids...)
}

// Mutation returns the SnapshotMutation object of the builder.
func (_u *SnapshotUpdateOne) Mutation() *SnapshotMutation {
	return _u.mutation
}

// ClearSnapshotEntries clears all "snapshot_entries" edges to the SnapshotEntry entity.
func (_u *SnapshotUpdateOne) ClearSnapshotEntries() *SnapshotUpdateOne {
	_u.mutation.ClearSnapshotEntries()
	return _u
}

// RemoveSnapshotEntryIDs removes the "snapshot_entries" edge to SnapshotEntry entities by IDs.
func (_u *SnapshotUpdateOne) RemoveSnapshotEntryIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.RemoveSnapshotEntryIDs(ids...)
	return _u
}

// RemoveSnapshotEntries removes "snapshot_entries" edges to SnapshotEntry entities.
func (_u *SnapshotUpdateOne) RemoveSnapshotEntries(v ...*SnapshotEntry) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotEntryIDs(ids...)
}

// Where appends a list predicates to the SnapshotUpdate builder.
func (_u *SnapshotUpdateOne) Where(ps ...predicate.Snapshot) *SnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SnapshotUpdateOne) Select(field string, fields ...string) *SnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Snapshot entity.
func (_u *SnapshotUpdateOne) Save(ctx context.Context) (*Snapshot, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SnapshotUpdateOne) SaveX(ctx context.Context) *Snapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SnapshotUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if snapshot.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized snapshot.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := snapshot.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SnapshotUpdateOne) check() error {
	if _u.mutation.HouseholdCleared() && len(_u.mutation.HouseholdIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Snapshot.household"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SnapshotUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SnapshotUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SnapshotUpdateOne) sqlSave(ctx context.Context) (_node *Snapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(snapshot.Table, snapshot.Columns, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Snapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, snapshot.FieldID)
		for _, f := range fields {
			if !snapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != snapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(snapshot.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(snapshot.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(snapshot.FieldNote, field.TypeString)
	}
	if _u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.SnapshotEntriesTable,
			Columns: []string{snapshot.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotEntriesIDs(); len(nodes) > 0 && !_u.mutation.SnapshotEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.SnapshotEntriesTable,
			Columns: []string{snapshot.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.SnapshotEntriesTable,
			Columns: []string{snapshot.SnapshotEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshotentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Snapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
