// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"beavermoney.app/ent/household"
	"beavermoney.app/ent/householdcurrency"
	"beavermoney.app/ent/snapshot"
	"beavermoney.app/ent/snapshotrate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
)

// SnapshotRateCreate is the builder for creating a SnapshotRate entity.
type SnapshotRateCreate struct {
	config
	mutation *SnapshotRateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetHouseholdID sets the "household_id" field.
func (_c *SnapshotRateCreate) SetHouseholdID(v int) *SnapshotRateCreate {
	_c.mutation.SetHouseholdID(v)
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SnapshotRateCreate) SetCreateTime(v time.Time) *SnapshotRateCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SnapshotRateCreate) SetNillableCreateTime(v *time.Time) *SnapshotRateCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SnapshotRateCreate) SetUpdateTime(v time.Time) *SnapshotRateCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SnapshotRateCreate) SetNillableUpdateTime(v *time.Time) *SnapshotRateCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetRate sets the "rate" field.
func (_c *SnapshotRateCreate) SetRate(v decimal.Decimal) *SnapshotRateCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetSnapshotID sets the "snapshot_id" field.
func (_c *SnapshotRateCreate) SetSnapshotID(v int) *SnapshotRateCreate {
	_c.mutation.SetSnapshotID(v)
	return _c
}

// SetFromHouseholdCurrencyID sets the "from_household_currency_id" field.
func (_c *SnapshotRateCreate) SetFromHouseholdCurrencyID(v int) *SnapshotRateCreate {
	_c.mutation.SetFromHouseholdCurrencyID(v)
	return _c
}

// SetToHouseholdCurrencyID sets the "to_household_currency_id" field.
func (_c *SnapshotRateCreate) SetToHouseholdCurrencyID(v int) *SnapshotRateCreate {
	_c.mutation.SetToHouseholdCurrencyID(v)
	return _c
}

// SetHousehold sets the "household" edge to the Household entity.
func (_c *SnapshotRateCreate) SetHousehold(v *Household) *SnapshotRateCreate {
	return _c.SetHouseholdID(v.ID)
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_c *SnapshotRateCreate) SetSnapshot(v *Snapshot) *SnapshotRateCreate {
	return _c.SetSnapshotID(v.ID)
}

// SetFromCurrencyID sets the "from_currency" edge to the HouseholdCurrency entity by ID.
func (_c *SnapshotRateCreate) SetFromCurrencyID(id int) *SnapshotRateCreate {
	_c.mutation.SetFromCurrencyID(id)
	return _c
}

// SetFromCurrency sets the "from_currency" edge to the HouseholdCurrency entity.
func (_c *SnapshotRateCreate) SetFromCurrency(v *HouseholdCurrency) *SnapshotRateCreate {
	return _c.SetFromCurrencyID(v.ID)
}

// SetToCurrencyID sets the "to_currency" edge to the HouseholdCurrency entity by ID.
func (_c *SnapshotRateCreate) SetToCurrencyID(id int) *SnapshotRateCreate {
	_c.mutation.SetToCurrencyID(id)
	return _c
}

// SetToCurrency sets the "to_currency" edge to the HouseholdCurrency entity.
func (_c *SnapshotRateCreate) SetToCurrency(v *HouseholdCurrency) *SnapshotRateCreate {
	return _c.SetToCurrencyID(v.ID)
}

// Mutation returns the SnapshotRateMutation object of the builder.
func (_c *SnapshotRateCreate) Mutation() *SnapshotRateMutation {
	return _c.mutation
}

// Save creates the SnapshotRate in the database.
func (_c *SnapshotRateCreate) Save(ctx context.Context) (*SnapshotRate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SnapshotRateCreate) SaveX(ctx context.Context) *SnapshotRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SnapshotRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SnapshotRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SnapshotRateCreate) defaults() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		if snapshotrate.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized snapshotrate.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := snapshotrate.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		if snapshotrate.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized snapshotrate.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := snapshotrate.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SnapshotRateCreate) check() error {
	if _, ok := _c.mutation.HouseholdID(); !ok {
		return &ValidationError{Name: "household_id", err: errors.New(`ent: missing required field "SnapshotRate.household_id"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "SnapshotRate.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "SnapshotRate.update_time"`)}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "SnapshotRate.rate"`)}
	}
	if _, ok := _c.mutation.SnapshotID(); !ok {
		return &ValidationError{Name: "snapshot_id", err: errors.New(`ent: missing required field "SnapshotRate.snapshot_id"`)}
	}
	if v, ok := _c.mutation.SnapshotID(); ok {
		if err := snapshotrate.SnapshotIDValidator(v); err != nil {
			return &ValidationError{Name: "snapshot_id", err: fmt.Errorf(`ent: validator failed for field "SnapshotRate.snapshot_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromHouseholdCurrencyID(); !ok {
		return &ValidationError{Name: "from_household_currency_id", err: errors.New(`ent: missing required field "SnapshotRate.from_household_currency_id"`)}
	}
	if v, ok := _c.mutation.FromHouseholdCurrencyID(); ok {
		if err := snapshotrate.FromHouseholdCurrencyIDValidator(v); err != nil {
			return &ValidationError{Name: "from_household_currency_id", err: fmt.Errorf(`ent: validator failed for field "SnapshotRate.from_household_currency_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToHouseholdCurrencyID(); !ok {
		return &ValidationError{Name: "to_household_currency_id", err: errors.New(`ent: missing required field "SnapshotRate.to_household_currency_id"`)}
	}
	if v, ok := _c.mutation.ToHouseholdCurrencyID(); ok {
		if err := snapshotrate.ToHouseholdCurrencyIDValidator(v); err != nil {
			return &ValidationError{Name: "to_household_currency_id", err: fmt.Errorf(`ent: validator failed for field "SnapshotRate.to_household_currency_id": %w`, err)}
		}
	}
	if len(_c.mutation.HouseholdIDs()) == 0 {
		return &ValidationError{Name: "household", err: errors.New(`ent: missing required edge "SnapshotRate.household"`)}
	}
	if len(_c.mutation.SnapshotIDs()) == 0 {
		return &ValidationError{Name: "snapshot", err: errors.New(`ent: missing required edge "SnapshotRate.snapshot"`)}
	}
	if len(_c.mutation.FromCurrencyIDs()) == 0 {
		return &ValidationError{Name: "from_currency", err: errors.New(`ent: missing required edge "SnapshotRate.from_currency"`)}
	}
	if len(_c.mutation.ToCurrencyIDs()) == 0 {
		return &ValidationError{Name: "to_currency", err: errors.New(`ent: missing required edge "SnapshotRate.to_currency"`)}
	}
	return nil
}

func (_c *SnapshotRateCreate) sqlSave(ctx context.Context) (*SnapshotRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SnapshotRateCreate) createSpec() (*SnapshotRate, *sqlgraph.CreateSpec) {
	var (
		_node = &SnapshotRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(snapshotrate.Table, sqlgraph.NewFieldSpec(snapshotrate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(snapshotrate.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(snapshotrate.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(snapshotrate.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	if nodes := _c.mutation.HouseholdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   snapshotrate.HouseholdTable,
			Columns: []string{snapshotrate.HouseholdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(household.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HouseholdID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   snapshotrate.SnapshotTable,
			Columns: []string{snapshotrate.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SnapshotID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FromCurrencyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   snapshotrate.FromCurrencyTable,
			Columns: []string{snapshotrate.FromCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FromHouseholdCurrencyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ToCurrencyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   snapshotrate.ToCurrencyTable,
			Columns: []string{snapshotrate.ToCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(householdcurrency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ToHouseholdCurrencyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SnapshotRate.Create().
//		SetHouseholdID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SnapshotRateUpsert) {
//			SetHouseholdID(v+v).
//		}).
//		Exec(ctx)
func (_c *SnapshotRateCreate) OnConflict(opts ...sql.ConflictOption) *SnapshotRateUpsertOne {
	_c.conflict = opts
	return &SnapshotRateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SnapshotRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SnapshotRateCreate) OnConflictColumns(columns ...string) *SnapshotRateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SnapshotRateUpsertOne{
		create: _c,
	}
}

type (
	// SnapshotRateUpsertOne is the builder for "upsert"-ing
	//  one SnapshotRate node.
	SnapshotRateUpsertOne struct {
		create *SnapshotRateCreate
	}

	// SnapshotRateUpsert is the "OnConflict" setter.
	SnapshotRateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *SnapshotRateUpsert) SetUpdateTime(v time.Time) *SnapshotRateUpsert {
	u.Set(snapshotrate.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SnapshotRateUpsert) UpdateUpdateTime() *SnapshotRateUpsert {
	u.SetExcluded(snapshotrate.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SnapshotRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SnapshotRateUpsertOne) UpdateNewValues() *SnapshotRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.HouseholdID(); exists {
			s.SetIgnore(snapshotrate.FieldHouseholdID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(snapshotrate.FieldCreateTime)
		}
		if _, exists := u.create.mutation.Rate(); exists {
			s.SetIgnore(snapshotrate.FieldRate)
		}
		if _, exists := u.create.mutation.SnapshotID(); exists {
			s.SetIgnore(snapshotrate.FieldSnapshotID)
		}
		if _, exists := u.create.mutation.FromHouseholdCurrencyID(); exists {
			s.SetIgnore(snapshotrate.FieldFromHouseholdCurrencyID)
		}
		if _, exists := u.create.mutation.ToHouseholdCurrencyID(); exists {
			s.SetIgnore(snapshotrate.FieldToHouseholdCurrencyID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SnapshotRate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SnapshotRateUpsertOne) Ignore() *SnapshotRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SnapshotRateUpsertOne) DoNothing() *SnapshotRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SnapshotRateCreate.OnConflict
// documentation for more info.
func (u *SnapshotRateUpsertOne) Update(set func(*SnapshotRateUpsert)) *SnapshotRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SnapshotRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SnapshotRateUpsertOne) SetUpdateTime(v time.Time) *SnapshotRateUpsertOne {
	return u.Update(func(s *SnapshotRateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SnapshotRateUpsertOne) UpdateUpdateTime() *SnapshotRateUpsertOne {
	return u.Update(func(s *SnapshotRateUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *SnapshotRateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SnapshotRateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SnapshotRateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SnapshotRateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SnapshotRateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SnapshotRateCreateBulk is the builder for creating many SnapshotRate entities in bulk.
type SnapshotRateCreateBulk struct {
	config
	err      error
	builders []*SnapshotRateCreate
	conflict []sql.ConflictOption
}

// Save creates the SnapshotRate entities in the database.
func (_c *SnapshotRateCreateBulk) Save(ctx context.Context) ([]*SnapshotRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SnapshotRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SnapshotRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SnapshotRateCreateBulk) SaveX(ctx context.Context) []*SnapshotRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SnapshotRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SnapshotRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SnapshotRate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SnapshotRateUpsert) {
//			SetHouseholdID(v+v).
//		}).
//		Exec(ctx)
func (_c *SnapshotRateCreateBulk) OnConflict(opts ...sql.ConflictOption) *SnapshotRateUpsertBulk {
	_c.conflict = opts
	return &SnapshotRateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SnapshotRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SnapshotRateCreateBulk) OnConflictColumns(columns ...string) *SnapshotRateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SnapshotRateUpsertBulk{
		create: _c,
	}
}

// SnapshotRateUpsertBulk is the builder for "upsert"-ing
// a bulk of SnapshotRate nodes.
type SnapshotRateUpsertBulk struct {
	create *SnapshotRateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SnapshotRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SnapshotRateUpsertBulk) UpdateNewValues() *SnapshotRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.HouseholdID(); exists {
				s.SetIgnore(snapshotrate.FieldHouseholdID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(snapshotrate.FieldCreateTime)
			}
			if _, exists := b.mutation.Rate(); exists {
				s.SetIgnore(snapshotrate.FieldRate)
			}
			if _, exists := b.mutation.SnapshotID(); exists {
				s.SetIgnore(snapshotrate.FieldSnapshotID)
			}
			if _, exists := b.mutation.FromHouseholdCurrencyID(); exists {
				s.SetIgnore(snapshotrate.FieldFromHouseholdCurrencyID)
			}
			if _, exists := b.mutation.ToHouseholdCurrencyID(); exists {
				s.SetIgnore(snapshotrate.FieldToHouseholdCurrencyID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SnapshotRate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SnapshotRateUpsertBulk) Ignore() *SnapshotRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SnapshotRateUpsertBulk) DoNothing() *SnapshotRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SnapshotRateCreateBulk.OnConflict
// documentation for more info.
func (u *SnapshotRateUpsertBulk) Update(set func(*SnapshotRateUpsert)) *SnapshotRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SnapshotRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SnapshotRateUpsertBulk) SetUpdateTime(v time.Time) *SnapshotRateUpsertBulk {
	return u.Update(func(s *SnapshotRateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SnapshotRateUpsertBulk) UpdateUpdateTime() *SnapshotRateUpsertBulk {
	return u.Update(func(s *SnapshotRateUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *SnapshotRateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SnapshotRateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SnapshotRateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SnapshotRateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
